### ISSUE TITLE
rcnn_10_100.tar.gz download speed

### ISSUE THREAD

**Issue by StepOITD** [facebookresearch/pythia#10]
![image](https://user-images.githubusercontent.com/14295658/45399765-ef7d5080-b67b-11e8-8d9f-ecb7204ddf2a.png)
dying downloading

**Comment by StepOITD** [comment]
Any faster source？

**Comment by StepOITD** [comment]
So that file is actually the features extracted from origin data？

**Comment by YuJiang01** [comment]
> So that file is actually the features extracted from origin data？

Yes, for this one, we used features directly from https://github.com/peteanderson80/bottom-up-attention
for features from detectron, you can follow here to extract image feature: https://github.com/facebookresearch/pythia/blob/master/data_prep/data_preprocess.md#extract-image-features

**Comment by curry111** [comment]
@YuJiang01 Hi :sweat_smile: :sweat_smile: If you used the rcnn_10_100 features directly from the other project, then How could you get the vqa_mirror features? I saw 2 folders in the rcnn_10_100 directory,

> vqa_mirror/train2014
> vqa_mirror/val2014
