### ISSUE TITLE
Detectron configs for demo

### ISSUE THREAD

**Issue by ggaemo** [facebookresearch/pythia#100]
## ❓ Questions and Help
What are the exact configurations for the detectron used in the demo for vqa2.0? 
!wget -O ~/pythia_home/content/model_data/detectron_model.pth  https://dl.fbaipublicfiles.com/pythia/detectron_model/detectron_model.pth 

The download link does not show the exact configurations

**Comment by apsdehal** [comment]
Hi, please fine it here https://dl.fbaipublicfiles.com/pythia/detectron_model/detectron_model.yaml

**Comment by ggaemo** [comment]
So this configuration is not the configuration that is used to win the VQA 2.0 challenge, right? The backbone is "R-101-FPN". Is it just for explaining how the 'basic and simple' version of pythia works? 

In pythia/configs/vqa/vqa2/pythia.yml the following shows.

 image_feature_encodings:
    - type: finetune_faster_rcnn_fpn_fc7
      params:
        bias_file: detectron/fc6/fc7_b.pkl
        weights_file: detectron/fc6/fc7_w.pkl
    - type: default

So what is the exact configuration of the detectron in this case?

In tools/extract_features.md it recommends "e2e_faster_rcnn_X-101-64x4d-FPN_1x_MLP_2048_FPN_512" which is a later model. Is the readme up to date?

**Comment by apsdehal** [comment]
The configuration linked above is the one used to extract out features which are further used in training the pythia model. Features are *separately extracted* and detector is not trained *end to end with the pythia model*. The layer that you are seeing in the pythia config is used for finetuning. We extract features from fc6 layers and thus fc7 layer is finetuned.

Again to clarify, detectron config is separate from pythia config and features are extracted out separately from pythia training.
