### ISSUE TITLE
Confusion about dealing fast-rcnn feature when running textvqa

### ISSUE THREAD

**Issue by lixiangpengcs** [facebookresearch/pythia#106]
## ❓ Questions and Help
I found in your code the dimension of faster rcnn feature is: batchsize x 137 x 2048. But the provided feature is 100 x 2048 and I saw you padding the other 37-dimension as 0. I don't know why you process features as this.

**Comment by apsdehal** [comment]
That's just a left over artifact from our research code, it shouldn't matter. You should consider them as 100 and you can change it to 100 if you are training from scratch.

**Comment by lixiangpengcs** [comment]
Thank your for your reply!

**Comment by lixiangpengcs** [comment]
I saw you provide Faster-RCNN feature including boxes, boxes feature and their confidences.  But there is no box corresponding labels in provided feature. Could you provide box labels feature of textVQA dataset?

**Comment by apsdehal** [comment]
We don't provide them out of the box, but you can use the feature extraction scripts: 
- https://github.com/facebookresearch/pythia/blob/master/tools/extract_features.py and https://github.com/facebookresearch/pythia/blob/master/tools/extract_features.md for extracting this information. Uncomment this part: https://github.com/facebookresearch/pythia/blob/master/tools/extract_features.py#L190...L198
- https://github.com/facebookresearch/pythia/blob/master/pythia/scripts/features/extract_features_vmb.py for VQA Maskrcnn Benchmark

**Comment by lixiangpengcs** [comment]
Thank your for your reply!
