### ISSUE TITLE
Questions about test accuracy of LoRRA

### ISSUE THREAD

**Issue by SelinaFelton** [facebookresearch/pythia#107]
## ❓ Questions and Help
What is the test accuracy of LoRRA in TestVQA dataset ?I only saw val accuracy in README.
How can I get test accuracy ? I have not saw any file which can calculate test accuracy yet.

**Comment by apsdehal** [comment]
Test accuracy has been reported in the paper https://arxiv.org/abs/1904.0892. You can calculate it on your end following challenge participation instructions at https://learnpythia.readthedocs.io/en/latest/tutorials/challenge.html. Do keep in mind that only 5 submissions are allowed on test-std.

**Comment by apsdehal** [comment]
Closing as resolved. Please open up a new issue if you face anything else. Thanks.

**Comment by SelinaFelton** [comment]
Thanks for your reply!
I saw the TextVQA dataset provided test dataset, can I calculate test accuracy directly using this test dataset?
