### ISSUE TITLE
c++extension failed to allocate memeory 

### ISSUE THREAD

**Issue by biexiangduo** [facebookresearch/pythia#108]
## ❓ Questions and Help
my gpu is gtx1060 6g, memory is 16g
when I run following command ,it occurs error.I don't know where is the problem ,my gpu memory too small? I try minimize batchsize to 1,it occur another problem.

pf@pf-N95TP6:~/pythia$ python tools/run.py --tasks vqa --datasets textvqa --model lorra --config configs/vqa/textvqa/lorra.yml 
WARNING: Device specified is 'cuda' but cuda is not present. Switching to CPU version
Logging to: ./save/vqa_textvqa_lorra_1234/logs/vqa_textvqa_lorra_1234_2019-06-24T11:14:41.log
2019-06-24T11:14:41 INFO: =====  Training Parameters    =====
2019-06-24T11:14:41 INFO: {
    "batch_size": 128,
    "clip_gradients": true,
    "clip_norm_mode": "all",
    "data_parallel": false,
    "device": "cpu",
    "distributed": false,
    "evalai_inference": false,
    "experiment_name": "run",
    "load_pretrained": false,
    "local_rank": null,
    "log_dir": "./logs",
    "log_interval": 100,
    "logger_level": "info",
    "lr_ratio": 0.01,
    "lr_scheduler": true,
    "lr_steps": [
        14000
    ],
    "max_epochs": null,
    "max_grad_l2_norm": 0.25,
    "max_iterations": 24000,
    "metric_minimize": false,
    "monitored_metric": "vqa_accuracy",
    "num_workers": 7,
    "patience": 4000,
    "pin_memory": false,
    "pretrained_mapping": {
        "image_feature_embeddings_list": "image_feature_embeddings_list",
        "image_feature_encoders": "image_feature_encoders",
        "image_text_multi_modal_combine_layer": "image_text_multi_modal_combine_layer",
        "text_embeddings": "text_embeddings"
    },
    "resume": false,
    "resume_file": null,
    "run_type": "train+inference",
    "save_dir": "./save",
    "seed": 1234,
    "should_early_stop": false,
    "should_not_log": false,
    "snapshot_interval": 1000,
    "task_size_proportional_sampling": true,
    "trainer": "base_trainer",
    "use_warmup": true,
    "verbose_dump": false,
    "warmup_factor": 0.2,
    "warmup_iterations": 1000
}
2019-06-24T11:14:41 INFO: ======  Task Attributes  ======
2019-06-24T11:14:41 INFO: ======== vqa/textvqa =======
2019-06-24T11:14:41 INFO: {
    "data_root_dir": "../data",
    "fast_read": false,
    "features_max_len": 137,
    "image_depth_first": false,
    "image_features": {
        "test": [
            "open_images/detectron_fix_100/fc6/test,open_images/resnet152/test"
        ],
        "train": [
            "open_images/detectron_fix_100/fc6/train,open_images/resnet152/train"
        ],
        "val": [
            "open_images/detectron_fix_100/fc6/train,open_images/resnet152/train"
        ]
    },
    "imdb_files": {
        "test": [
            "imdb/textvqa_0.5/imdb_textvqa_test.npy"
        ],
        "train": [
            "imdb/textvqa_0.5/imdb_textvqa_train.npy"
        ],
        "val": [
            "imdb/textvqa_0.5/imdb_textvqa_val.npy"
        ]
    },
    "processors": {
        "answer_processor": {
            "params": {
                "context_preprocessor": {
                    "params": {},
                    "type": "simple_word"
                },
                "max_length": 50,
                "num_answers": 10,
                "preprocessor": {
                    "params": {},
                    "type": "simple_word"
                },
                "vocab_file": "vocabs/answers_textvqa_more_than_1.txt"
            },
            "type": "soft_copy_answer"
        },
        "bbox_processor": {
            "params": {
                "max_length": 50
            },
            "type": "bbox"
        },
        "context_processor": {
            "params": {
                "max_length": 50,
                "model_file": ".vector_cache/wiki.en.bin"
            },
            "type": "fasttext"
        },
        "ocr_token_processor": {
            "params": {},
            "type": "simple_word"
        },
        "text_processor": {
            "params": {
                "max_length": 14,
                "preprocessor": {
                    "params": {},
                    "type": "simple_sentence"
                },
                "vocab": {
                    "embedding_name": "glove.6B.300d",
                    "type": "intersected",
                    "vocab_file": "vocabs/vocabulary_100k.txt"
                }
            },
            "type": "vocab"
        }
    },
    "return_info": true,
    "use_ocr": true,
    "use_ocr_info": false
}
2019-06-24T11:14:41 INFO: ======  Optimizer Attributes  ======
2019-06-24T11:14:41 INFO: {
    "params": {
        "eps": 1e-08,
        "lr": 0.01,
        "weight_decay": 0
    },
    "type": "Adamax"
}
2019-06-24T11:14:41 INFO: ======  Model (lorra) Attributes  ======
2019-06-24T11:14:41 INFO: {
    "classifier": {
        "params": {
            "img_hidden_dim": 5000,
            "text_hidden_dim": 300
        },
        "type": "logit"
    },
    "context_embeddings": [
        {
            "params": {
                "embedding_dim": 350
            },
            "type": "identity"
        }
    ],
    "context_feature_dim": 300,
    "context_feature_embeddings": [
        {
            "modal_combine": {
                "params": {
                    "dropout": 0,
                    "hidden_dim": 5000
                },
                "type": "non_linear_element_multiply"
            },
            "normalization": "sigmoid",
            "transform": {
                "params": {
                    "out_dim": 1
                },
                "type": "linear"
            }
        }
    ],
    "context_feature_encodings": [
        {
            "params": {},
            "type": "default"
        }
    ],
    "context_max_len": 50,
    "image_feature_dim": 2048,
    "image_feature_embeddings": [
        {
            "modal_combine": {
                "params": {
                    "dropout": 0,
                    "hidden_dim": 5000
                },
                "type": "non_linear_element_multiply"
            },
            "normalization": "softmax",
            "transform": {
                "params": {
                    "out_dim": 1
                },
                "type": "linear"
            }
        }
    ],
    "image_feature_encodings": [
        {
            "params": {
                "bias_file": "detectron/fc6/fc7_b.pkl",
                "weights_file": "detectron/fc6/fc7_w.pkl"
            },
            "type": "finetune_faster_rcnn_fpn_fc7"
        },
        {
            "params": {},
            "type": "default"
        }
    ],
    "image_text_modal_combine": {
        "params": {
            "context_dim": 350,
            "dropout": 0,
            "hidden_dim": 5000
        },
        "type": "non_linear_element_multiply"
    },
    "losses": [
        {
            "type": "logit_bce"
        }
    ],
    "metrics": [
        {
            "type": "vqa_accuracy"
        }
    ],
    "model_data_dir": "../data",
    "num_context_features": 1,
    "text_embeddings": [
        {
            "params": {
                "conv1_out": 512,
                "conv2_out": 2,
                "dropout": 0,
                "embedding_dim": 300,
                "hidden_dim": 1024,
                "kernel_size": 1,
                "num_layers": 1,
                "padding": 0
            },
            "type": "attention"
        }
    ]
}
2019-06-24T11:14:41 INFO: Loading tasks and data
2019-06-24T11:14:45 INFO: Torch version is: 1.0.1.post2
2019-06-24T11:14:45 INFO: ===== Model =====
2019-06-24T11:14:45 INFO: LoRRA(
  (text_embeddings): ModuleList(
    (0): TextEmbedding(
      (module): AttentionTextEmbedding(
        (recurrent_unit): LSTM(300, 1024, batch_first=True)
        (dropout): Dropout(p=0)
        (conv1): Conv1d(1024, 512, kernel_size=(1,), stride=(1,))
        (conv2): Conv1d(512, 2, kernel_size=(1,), stride=(1,))
        (relu): ReLU()
      )
    )
  )
  (context_embeddings): ModuleList(
    (0): TextEmbedding(
      (module): Identity()
    )
  )
  (context_feature_encoders): ModuleList(
    (0): ImageEncoder(
      (module): Identity()
    )
  )
  (context_feature_embeddings_list): ModuleList(
    (0): ModuleList(
      (0): ImageEmbedding(
        (image_attention_model): AttentionLayer(
          (module): TopDownAttention(
            (combination_layer): ModalCombineLayer(
              (module): NonLinearElementMultiply(
                (fa_image): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=300, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (fa_txt): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (fa_context): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (dropout): Dropout(p=0)
              )
            )
            (transform): TransformLayer(
              (module): LinearTransform(
                (lc): Linear(in_features=5000, out_features=1, bias=True)
              )
            )
          )
        )
      )
    )
  )
  (word_embedding): Embedding(75505, 300)
  (image_feature_encoders): ModuleList(
    (0): ImageEncoder(
      (module): FinetuneFasterRcnnFpnFc7(
        (lc): Linear(in_features=2048, out_features=2048, bias=True)
      )
    )
    (1): ImageEncoder(
      (module): Identity()
    )
  )
  (image_feature_embeddings_list): ModuleList(
    (0): ModuleList(
      (0): ImageEmbedding(
        (image_attention_model): AttentionLayer(
          (module): TopDownAttention(
            (combination_layer): ModalCombineLayer(
              (module): NonLinearElementMultiply(
                (fa_image): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (fa_txt): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (fa_context): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (dropout): Dropout(p=0)
              )
            )
            (transform): TransformLayer(
              (module): LinearTransform(
                (lc): Linear(in_features=5000, out_features=1, bias=True)
              )
            )
          )
        )
      )
    )
    (1): ModuleList(
      (0): ImageEmbedding(
        (image_attention_model): AttentionLayer(
          (module): TopDownAttention(
            (combination_layer): ModalCombineLayer(
              (module): NonLinearElementMultiply(
                (fa_image): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (fa_txt): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (fa_context): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (dropout): Dropout(p=0)
              )
            )
            (transform): TransformLayer(
              (module): LinearTransform(
                (lc): Linear(in_features=5000, out_features=1, bias=True)
              )
            )
          )
        )
      )
    )
  )
  (image_text_multi_modal_combine_layer): ModalCombineLayer(
    (module): NonLinearElementMultiply(
      (fa_image): ReLUWithWeightNormFC(
        (layers): Sequential(
          (0): Linear(in_features=4096, out_features=5000, bias=True)
          (1): ReLU()
        )
      )
      (fa_txt): ReLUWithWeightNormFC(
        (layers): Sequential(
          (0): Linear(in_features=2048, out_features=5000, bias=True)
          (1): ReLU()
        )
      )
      (fa_context): ReLUWithWeightNormFC(
        (layers): Sequential(
          (0): Linear(in_features=350, out_features=5000, bias=True)
          (1): ReLU()
        )
      )
      (dropout): Dropout(p=0)
    )
  )
  (classifier): ClassifierLayer(
    (module): LogitClassifier(
      (f_o_text): ReLUWithWeightNormFC(
        (layers): Sequential(
          (0): Linear(in_features=10000, out_features=300, bias=True)
          (1): ReLU()
        )
      )
      (f_o_image): ReLUWithWeightNormFC(
        (layers): Sequential(
          (0): Linear(in_features=10000, out_features=5000, bias=True)
          (1): ReLU()
        )
      )
      (linear_text): Linear(in_features=300, out_features=4047, bias=True)
      (linear_image): Linear(in_features=5000, out_features=4047, bias=True)
    )
  )
  (loss): Losses()
)
2019-06-24T11:14:45 INFO: Starting training...
2019-06-24T11:14:45 INFO: Fetching fastText model for OCR processing
2019-06-24T11:14:45 INFO: Loading fasttext model now from /home/pf/pythia/pythia/.vector_cache/wiki.en.bin
2019-06-24T11:14:45 ERROR: Traceback (most recent call last):
  File "fasttext/fasttext.pyx", line 152, in fasttext.fasttext.load_model
RuntimeError: vector::_M_default_append

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pf/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pf/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pf/pythia/pythia/tasks/multi_task.py", line 73, in __getitem__
    item = self.chosen_task[idx]
  File "/home/pf/pythia/pythia/tasks/base_task.py", line 155, in __getitem__
    item = self.chosen_dataset[idx]
  File "/home/pf/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 81, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/pf/pythia/pythia/tasks/base_dataset.py", line 49, in __getitem__
    sample = self.get_item(idx)
  File "/home/pf/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 93, in get_item
    return self.load_item(idx)
  File "/home/pf/pythia/pythia/tasks/vqa/vizwiz/dataset.py", line 16, in load_item
    sample = super().load_item(idx)
  File "/home/pf/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 124, in load_item
    current_sample = self.add_ocr_details(sample_info, current_sample)
  File "/home/pf/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 139, in add_ocr_details
    context = self.context_processor({"tokens": ocr_tokens})
  File "/home/pf/pythia/pythia/tasks/processors.py", line 155, in __call__
    return self.processor(item)
  File "/home/pf/pythia/pythia/tasks/processors.py", line 492, in __call__
    self._try_download()
  File "/home/pf/pythia/pythia/tasks/processors.py", line 407, in _try_download
    self._load_fasttext_model(model_file)
  File "/home/pf/pythia/pythia/tasks/processors.py", line 466, in _load_fasttext_model
    self.model = load_model(model_file)
  File "fasttext/fasttext.pyx", line 154, in fasttext.fasttext.load_model
Exception: fastText: Cannot load /home/pf/pythia/pythia/.vector_cache/wiki.en.bin due to C++ extension failed to allocate the memory

Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 83, in run
    trainer.train()
  File "/home/pf/pythia/pythia/trainers/base_trainer.py", line 217, in train
    for batch in self.train_loader:
  File "/home/pf/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/pf/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
Exception: Traceback (most recent call last):
  File "fasttext/fasttext.pyx", line 152, in fasttext.fasttext.load_model
RuntimeError: vector::_M_default_append

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pf/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pf/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pf/pythia/pythia/tasks/multi_task.py", line 73, in __getitem__
    item = self.chosen_task[idx]
  File "/home/pf/pythia/pythia/tasks/base_task.py", line 155, in __getitem__
    item = self.chosen_dataset[idx]
  File "/home/pf/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 81, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/pf/pythia/pythia/tasks/base_dataset.py", line 49, in __getitem__
    sample = self.get_item(idx)
  File "/home/pf/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 93, in get_item
    return self.load_item(idx)
  File "/home/pf/pythia/pythia/tasks/vqa/vizwiz/dataset.py", line 16, in load_item
    sample = super().load_item(idx)
  File "/home/pf/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 124, in load_item
    current_sample = self.add_ocr_details(sample_info, current_sample)
  File "/home/pf/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 139, in add_ocr_details
    context = self.context_processor({"tokens": ocr_tokens})
  File "/home/pf/pythia/pythia/tasks/processors.py", line 155, in __call__
    return self.processor(item)
  File "/home/pf/pythia/pythia/tasks/processors.py", line 492, in __call__
    self._try_download()
  File "/home/pf/pythia/pythia/tasks/processors.py", line 407, in _try_download
    self._load_fasttext_model(model_file)
  File "/home/pf/pythia/pythia/tasks/processors.py", line 466, in _load_fasttext_model
    self.model = load_model(model_file)
  File "fasttext/fasttext.pyx", line 154, in fasttext.fasttext.load_model
Exception: fastText: Cannot load /home/pf/pythia/pythia/.vector_cache/wiki.en.bin due to C++ extension failed to allocate the memory

**Comment by apsdehal** [comment]
Hi. Yes, this is a memory issue. You atleast require 8GB memory to fit fastText.

**Comment by yash0307** [comment]
@apsdehal , I am having the same issue. I checked and my system has 435GB available (p3.16x). Can something else cause this ? For instance, [This issue](https://github.com/salestock/fastText.py/issues/115) suggests that it can also be due to version conflicts.

**Comment by apsdehal** [comment]
@yash0307 For FastText I am on commit 25c3994. Can you checkout that commit on your end (rerun the fasttext installation) and try again. Let me know if that works and I can push a fix with that specific version of fastText used in installation.

**Comment by apsdehal** [comment]
I discussed with some other users, I don't think it is an issue with fastText version. It is most probably an issue with your wiki.en.bin version. Can you post the md5 checksum for your wiki.en.bin file by running:
```
md5sum ~/pythia/pythia/.vector_cache/wiki.en.bin
```

It should be 92341f7f94c1801db19bb6b114fddff9.

**Comment by yash0307** [comment]
md5sum returned the same sting: 92341f7f94c1801db19bb6b114fddff9

**Comment by apsdehal** [comment]
And what commit you are on for fastText?

**Comment by yash0307** [comment]
Sorry for the late response. The issue was with the fastText version, I reversed the changes to commit 25c3994 and it worked fine.

**Comment by apsdehal** [comment]
Closing as this indeed seems like an issue with fasttext version.
