### ISSUE TITLE
[evaluation] Fix the gap between evaluation on EvalAI and in Pythia

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/pythia#109]
## 🐛 Bug

Due to contractions and other stuff there is always a gap in between the validation performance on Pythia side and EvalAI side. This gap should probably be fixed at the end evaluation for the validation and test accuracies calculation.

## Expected behavior

Accuracies from Pythia and EvalAI should be same.

**Comment by apsdehal** [comment]
FWIW, this only happens in LoRRA based architecture as Pythia based architectures use VQA vocabularies which are already processed using `process_answers.py`.

**Comment by vedanuj** [comment]
Running the evaluation code here : `https://github.com/GT-Vision-Lab/VQA/blob/master/PythonEvaluationTools/vqaEvaluation/vqaEval.py` gives a different accuracy compared to EvalAI for TextVQA. 

Test run on Validation phase with [submission file](https://evalai.s3.amazonaws.com/media/submission_files/submission_31880/506102f4-5916-48f2-94c8-d76bd53355e6.json) gives an accuracy of 27.4 whereas running the same file using the code given in the script results in 26.41 accuracy.

Is there any way to check if the EvalAI evaluation code is same as in the above script or are there any differences?
