### ISSUE TITLE
Some questions about the demo

### ISSUE THREAD

**Issue by Lausannen** [facebookresearch/pythia#11]
Hi , I am trying to run the demo, but when I load the pretrained model ,something is wrong,just like this:

RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/THCTensorCopy.cu:31
During handling of the above exception, another exception occurred:
RuntimeError: While copying the parameter named question_embedding_models.0.embedding.weight, whose dimensions in the model are torch.Size([25541, 300]) and whose dimensions in the checkpoint are torch.Size([17871, 300]).

If you have time ,I wish you can help me ! Thank you very much!

**Comment by Lausannen** [comment]
Really thank you for your suggestion! I have run the code successfully. 
However , when I used the pretrained model which was downloaded from Readme.md (detectron_100_resnet_most_data.tar.gz) , I found that the multi_modal_combine.Fa_image.main.0.weigth_v layer's dimension was [5000,4096],while the same layer's dimension in the model I was constructing was [5000,2048].
Finally , I changed the model code ,and successfully loaded the data. I think some notice should be added to the readme if someone else wants to run the demo .  If I misunderstood it , please let me know.
Thank you again!!

**Comment by Lausannen** [comment]
@meetshah1995 
Really thank you for your suggestion! I have run the code successfully.
However , when I used the pretrained model which was downloaded from Readme.md (detectron_100_resnet_most_data.tar.gz) , I found that the multi_modal_combine.Fa_image.main.0.weigth_v layer's dimension was [5000,4096],while the same layer's dimension in the model I was constructing was [5000,2048].
Finally , I changed the model code ,and successfully loaded the data. I think some notice should be added to the readme if someone else wants to run the demo . If I misunderstood it , please let me know.
Thank you again!!

**Comment by vishalprabha** [comment]
@Lausannen What Model code did you change, could you share the changes.

**Comment by apsdehal** [comment]
No longer applicable after new version and colab demo. please reopen the issue if there is some issue with the new demo. Closing for now.
