### ISSUE TITLE
Question about TextVQA dataset's test part

### ISSUE THREAD

**Issue by SelinaFelton** [facebookresearch/pythia#110]
## ❓ Questions and Help
I saw the TextVQA dataset provided test dataset, can I calculate test accuracy directly using this test dataset?

**Comment by apsdehal** [comment]
Hi,
The test set provided has only questions. To evaluate accuracy on test set, you will have to upload to EvalAI. Follow instructions in challenge participation to generate json file for your model and upload it to EvalAI.

**Comment by SelinaFelton** [comment]
Thanks, my problem is solved.
