### ISSUE TITLE
Incorrect model and config files in extract_features_vmb.py 

### ISSUE THREAD

**Issue by angelaslin** [facebookresearch/pythia#113]
## 🐛 Bug

There is a mismatch between the model and config file used in pythia/pythia/scripts/features/extract_features_vmb.py.

## Command

python3 pythia/scripts/features/extract_features_vmb.py --image_dir data/images --model_file data/detectron_model.pth --config_file data/detectron_model.yaml

## To Reproduce

1. Download the model and config file in extract_features_vmb.py and put them in the data directory.
2. python3 pythia/scripts/features/extract_features_vmb.py --image_dir data/images --model_file data/detectron_model.pth --config_file data/detectron_model.yaml

Traceback (most recent call last):
  File "pythia/scripts/features/extract_features_vmb.py", line 198, in <module>
    feature_extractor = FeatureExtractor()
  File "pythia/scripts/features/extract_features_vmb.py", line 34, in __init__
    self.detection_model = self._build_detection_model()
  File "pythia/scripts/features/extract_features_vmb.py", line 70, in _build_detection_model
    cfg.merge_from_file(self.args.config_file)
  File "/data/anaconda/envs/maskrcnn/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/data/anaconda/envs/maskrcnn/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/data/anaconda/envs/maskrcnn/lib/python3.7/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/data/anaconda/envs/maskrcnn/lib/python3.7/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/data/anaconda/envs/maskrcnn/lib/python3.7/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS'

## Expected behavior

I expected the script to extract features for objects in the image.

## Environment
 - PyTorch Version (e.g., 1.0): '1.0.0.dev20190328'
 - OS (e.g., Linux): Ubuntu 16.04.6 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): I followed the directions on the README and the installation instructions for Mask-RCNN (https://github.com/facebookresearch/maskrcnn-benchmark).
 - Python version: 3.7.3
 - CUDA/cuDNN version: Cuda 10.0.130 / cuDNN 7.4.2
 - GPU models and configuration: 1 Tesla P100

## Additional context

I installed PyTorch version 1.0.0.dev20190328 to get Mask-RCNN to run properly. The Mask-RCNN demo (https://github.com/facebookresearch/maskrcnn-benchmark#inference-in-a-few-lines) works properly for me.

**Comment by apsdehal** [comment]
Hi,
The problem is the version of maskrcnn-benchmark that you are using. Apologies for the confusion. Can you reinstall with our inhouse version of maskrcnn-benchmark from http://gitlab.com/meetshah1995/vqa-maskrcnn-benchmark and try again? 

Thanks.

**Comment by angelaslin** [comment]
Thank you! It works now. 

You should change `_save_feature()` function in the script to save the `info` dictionary as a different format such as the pickle format. I get this error (`ValueError: Array can't be memory-mapped: Python objects in dtype.`) when I try to load the `info` dictionary from the npy file.

**Comment by apsdehal** [comment]
How are you loading them? Use `np.load("<info_file_path.npy>", allow_pickle=True)`.

**Comment by angelaslin** [comment]
I used `features = np.load("output/<info_file_path.npy>", "r", allow_pickle=True)`. The object loads correctly when I use the command you suggested. Thank you!
