### ISSUE TITLE
Where is the module to detect and read text tokens?

### ISSUE THREAD

**Issue by DangDinhQuocTrung** [facebookresearch/pythia#115]
## ❓ Questions and Help
Hi, could you please tell me where the OCR module is located in the code?
I read that the OCR module is Rosetta. This module is in the code, or is it located in another repository or service?
Is there anyway that I can change it to other OCR modules?

**Comment by apsdehal** [comment]
Rosetta is an internal FB OCR system which is not public. You can read more upon it at https://code.fb.com/ai-research/rosetta-understanding-text-in-images-and-videos-with-machine-learning/. If you want to change it to other OCR modules, I would suggest you to update and create new IMDBs from original TextVQA IMDBs where you replace the `ocr_tokens` key with the tokens you generate. An example of other OCR system that can be used is Google's CloudVision API.
