### ISSUE TITLE
Preparing a New Dataset for Image Captioning Training

### ISSUE THREAD

**Issue by sarahallen111** [facebookresearch/pythia#117]
## ❓ Questions and Help
I'm sorry if this is very basic, but I'm new to the machine learning research community and have never done training before. I did go through the tutorial on how to use the pre-trained model for the image captioning (works fine), and read through the documentation about where to put the data and the commands for training. It seems the main things one needs is the features from the images and an ImDB. 

So, my questions:
1) Can you get the features simply by using the get_detectron_features function from the demo (PythiaDemo) for each image? Also, I noticed that in the VQA demo there's also a get_resnet_features function that is not included in the image captioning demo. Do you also need the resnet features for image captioning, or just the detectron features?

2) What is the format of the ImDB? I understand that it's essentially an array of dictionaries turned into a .npy file (through np.array() and np.save()), but what exactly goes inside of it? I found an example of doing this for VQA in build_vqa_2.0_imdb.py (in the legacy folder), but presumably the contents would be different for an image captioning problem instead of the VQA problem.

Thank you so much for helping a newbie out.

**Comment by apsdehal** [comment]
Hi,

> 1. Can you get the features simply by using the get_detectron_features function from the demo (PythiaDemo) for each image? Also, I noticed that in the VQA demo there's also a get_resnet_features function that is not included in the image captioning demo. Do you also need the resnet features for image captioning, or just the detectron features?

If you are planning to use the BUTD model, detectron features alone can work. Yes, you can use that function or use the script for extraction https://github.com/facebookresearch/pythia/blob/master/tools/extract_features.py. 

> 2. What is the format of the ImDB? I understand that it's essentially an array of dictionaries turned into a .npy file (through np.array() and np.save()), but what exactly goes inside of it? I found an example of doing this for VQA in build_vqa_2.0_imdb.py (in the legacy folder), but presumably the contents would be different for an image captioning problem instead of the VQA problem.

Yes, you are right. So, in ImDB, you put stuff which you require in your dataset class. It can be done without ImDB too but that will require implementing dataset from scratch. See tutorial on adding a dataset at https://learnpythia.readthedocs.io/en/latest/tutorials/dataset.html. Please check the ImDB for COCO (link in README) to understand what exactly is required for captioning.

**Comment by pidugusundeep** [comment]
@apsdehal Please update the link for `extract_features.py`
