### ISSUE TITLE
[Feature] Nucleus Sampling algorithm for text decoding

### ISSUE THREAD

**Issue by ishan-maheshwari** [facebookresearch/pythia#118]
## 🚀 Feature

Nucleus Sampling is a new text decoding strategy that avoids likelihood maximization. Rather, it works by sampling from the smallest set of top tokens which have a cumulative probability greater than a specified threshold. (https://arxiv.org/pdf/1904.09751.pdf)

## Motivation

Present text decoding strategies like beam search do not work well on open-ended generation tasks (even on strong language models like GPT-2). They tend to repeat text a lot and the main reason behind it is that they try to maximize likelihood, which is a contrast from human-generated text which has a mix of high and low probability tokens. 

Nucleus Sampling is a stochastic approach and resolves this issue. Moreover, it improves upon other stochastic methods like top-k sampling by choosing the right amount of tokens to sample from. The overall result is better text generation on the same language model.

## Pitch

I intend to create a function that implements Nucleus Sampling algorithm. The function can be called when the user wants to use Nucleus Sampling as text decoder in their model.

**Comment by apsdehal** [comment]
@ishan-maheshwari do you plan to work on this? Because at the moment we atleast don't have this on the Roadmap.

**Comment by ishan-maheshwari** [comment]
Hi! Yes, I'm currently working on this. 🙂

**Comment by ishan-maheshwari** [comment]
Can this issue be closed @apsdehal?

**Comment by apsdehal** [comment]
Thanks for reminding @ishan-maheshwari. Looking forward to more contributions from you in future.

Closed via #135.
