### ISSUE TITLE
[bug] Incorrect class labels predicted in extract_features_vmb.py

### ISSUE THREAD

**Issue by angelaslin** [facebookresearch/pythia#125]
## 🐛 Bug

extract_features_vmb.py saves the wrong class labels in the "objects" key in the info dictionary.
File: `pythia/scripts/features/extract_features_vmb.py`
Line 133: `objects = torch.argmax(scores[keep_boxes], dim=1)`

This line does not exclude the background class (index 0 of the `scores` vector). Sometimes the score for the background class is larger than the confidence scores saved in `max_conf` (which is computed over the non-background classes). In those cases, this line saves the background class instead of the class selected through non-maximum suppression. 

I propose to change this line to:
`objects = torch.argmax(scores[keep_boxes][:, 1:], dim=1)`

This change also has the added benefit of aligning the object index saved in `objects` with the indices of the objects in the category mapping for Visual Genome (https://dl.fbaipublicfiles.com/pythia/data/visual_genome_categories.json).

**Comment by apsdehal** [comment]
Thanks @angelaslin. Would you like to make a PR for this?

**Comment by angelaslin** [comment]
I have created a pull request!

**Comment by apsdehal** [comment]
Closed via #127.
