### ISSUE TITLE
403 Forbidden when downloading the models for ensembling

### ISSUE THREAD

**Issue by back2yes** [facebookresearch/pythia#13]
Hi, thanks for sharing your excellent work.
I want to have a try on ensembling the 30 models which produces the highest score, however when I download the models hosted on https://s3-us-west-1.amazonaws.com/pythia-vqa/ensembled.tar.gz, it says: ` AccessDeniedAccess Denied052D4426298A2296MSgYIY2Ao5g//jFFqs6hZZnHxzzjrOE+h6yusooey8qvEDe0Ghy1IvDiXooZMwh3P97JEO84dgU= `

Is there a way that I can access the models? Thanks again~

**Comment by YuJiang01** [comment]
The permission should be correct now

**Comment by YuJiang01** [comment]
@back2yes , Did you download these ensembled files when the issue is fixed? If so, would you mind share us a copy? we recently lost these files
