### ISSUE TITLE
Why is the value of bounding box in ocr_info so small?

### ISSUE THREAD

**Issue by fliu2013** [facebookresearch/pythia#130]
## ❓ Questions and Help
In imdb of textvqa, I find that figures of bounding box in ocr_info is almost less than 1 even for a 1024 * 667 image. I wonder how you guys process those figures. How can I get the original image region according to the bounding box?

**Comment by apsdehal** [comment]
I am not sure I understand what exactly you mean. You need to multiply the coordinates provided in ocr info with image's width and height.

**Comment by fliu2013** [comment]
Thanks a lot!
