### ISSUE TITLE
More evaluation metrics for captioning

### ISSUE THREAD

**Issue by Vimos** [facebookresearch/pythia#132]
In README, the line `BLEU 1 - 76.02, BLEU 4 - 35.42 , METEOR - 27.39, ROUGE_L - 56.17, CIDEr - 112.03 , SPICE - 20.33` shows several evaluation metrics, while only `BLEU 4` is offered in `pythia`.

Is there any plan adding other evaluation metrics? Or the users are required to implement their own?

**Comment by apsdehal** [comment]
You can use this script: https://github.com/facebookresearch/pythia/blob/master/pythia/scripts/coco/coco_caption_eval.py to calculate all of the metrics. We don't calculate anything other than BLEU4 at the runtime due to computational constraints.
