### ISSUE TITLE
About the copy module of LoRRA

### ISSUE THREAD

**Issue by liiiiiiiiil** [facebookresearch/pythia#136]
## ❓ Questions and Help
I read your 'text-vqa' paper, in which the copy module attract me a lot. But I can't find this module in your code. Did you opensource this code or rename it? thanks!

**Comment by apsdehal** [comment]
The copy mechanism works this way: You add a dynamic answer space to your model (this means that original VQA answer space will be extended by the size of your dynamic answer space, in this case, 50 for OCR tokens). Then when you are predicting the final answer, if the model predicts from this dynamic answer space, you copy the OCR token at the selected location.

Related source code points:
SoftCopyAnswerProcessor: https://github.com/facebookresearch/pythia/blob/master/pythia/tasks/processors.py#L681
Copy on prediction: https://github.com/facebookresearch/pythia/blob/master/pythia/tasks/vqa/vqa2/dataset.py#L183

**Comment by liiiiiiiiil** [comment]
thank you very much!
