### ISSUE TITLE
some question about extracting features?

### ISSUE THREAD

**Issue by liiiiiiiiil** [facebookresearch/pythia#143]
## ❓ Questions and Help
I wan't use the dataset named "ST-VQA", so I should extract the feature myself. I have some question:
1. what's the difference between pythia/scripts/extract_features_vmb.py and tools/extract_features.py ?
2. I tried to use tools/extract_features.py and I use docker to build detectron environment. But when I run the extract_features.py, it says there are modules named common.test_engine.
Please and Thanks

**Comment by apsdehal** [comment]
For 2. you need to have detectron in your PYTHON_PATH.
Ideally, for now you should use `extract_features_vmb.py` which is based on our custom fork of maskrcnn-benchmark.

**Comment by liiiiiiiiil** [comment]
> For 2. you need to have detectron in your PYTHON_PATH.
> Ideally, for now you should use `extract_features_vmb.py` which is based on our custom fork of maskrcnn-benchmark.

thanks very much!

**Comment by liiiiiiiiil** [comment]
I run this extract_features_vmb.py, however it's **incompatible** with the new version of maskrcnn-benchmark.
when I load the detectron_model.pth,the error shows like this:
KeyError: 'Non-existent config key: MODEL:BACKBONE.OUT_CHANELS

**Comment by apsdehal** [comment]
You have to use vqa_maskrcnn_benchmark https://gitlab.com/meetshah1995/vqa-maskrcnn-benchmark/

**Comment by liiiiiiiiil** [comment]
> You have to use vqa_maskrcnn_benchmark https://gitlab.com/meetshah1995/vqa-maskrcnn-benchmark/

Sorry to disturbing you, but I really want to use your code to do some work. I have some other question.
1. Why the standard maskrcnn-benchmark can not be use and What is the bigget difference between vqa-maskrcnn-benchmark with maskrcnn-benchmark?
2. When I install vqa-maskrcnn-benchmark by dockerfile, I found that the dockerfile still work for standard maskrcnn-benchmark, so how to install it?
thanks

**Comment by apsdehal** [comment]
1. We use extra attribute based loss to train this detector and it is trained on visual genome.
2. See the how we install in the demo here: https://colab.research.google.com/drive/1Z9fsh10rFtgWe4uy8nvU4mQmqdokdIRR

**Comment by liiiiiiiiil** [comment]
Thanks a lot!!!
