### ISSUE TITLE
Segmentation Fault（coredump）

### ISSUE THREAD

**Issue by haoopan** [facebookresearch/pythia#147]
## ❓ Questions and Help
Hi ：
  Thank you first to read my question. I set the num_works=0,but get the fault of 'Segmentation Fault（coredump）'. When set the num_works>0, It get the error of 'RuntimeError: DataLoader worker (pid(s) 10306) exited unexpectedly'.
  So, could please give me some tips. Thanks!

**Comment by apsdehal** [comment]
Seems like a memory issue. This is a common bug with low memory. Google for it. :) You would either want to use num_workers=0 or increase your memory
..

**Comment by pidugusundeep** [comment]
Even with using `num_workes=0` it stops running with just showing `Killed`, is memory the only reason? as iam running on 20G memory and 4 cores machine.
