### ISSUE TITLE
How do you build your vacabulary?

### ISSUE THREAD

**Issue by liiiiiiiiil** [facebookresearch/pythia#149]
## ❓ Questions and Help
For dataset text-vqa, you have two answers vocabulary: answers_textvqa_8k.txt and answers_textvqa_more_than_1.txt.
I tried to build a "more than 1" vocab on text-vqa's answers, but I find my vocab(12318) is  much bigger than your vocabulary(3997)? 
And how to build the 8k vocabulary?

**Comment by liiiiiiiiil** [comment]
I find the answer in your paper,
"  For our approach, we use a vocabulary SA of size
3996, which contains answers which appear at least twice
in the training set. For the baselines that don’t use the copy
mechanism, this vocabulary turns out to be too limited. To
give them a fair shot, we also create a larger vocabulary
(LA), containing the 8000 most frequent answers.  "

**Comment by liiiiiiiiil** [comment]
I tried to build a vacab for answers as you did, but my vacab is biger than yours? did you provide code for extracting answers vocab? Or just use the code "pythia->pythia->scripts->extract_vacabuary.py" ,but I find this code is for extract question vocab.

**Comment by apsdehal** [comment]
Try the following colab: https://colab.research.google.com/drive/1szmipJ6ugEHjJg0ie30j_nChworMYlKx
It has code for generating the answer vocabs.
