### ISSUE TITLE
docker demo doesnt run

### ISSUE THREAD

**Issue by hughperkins** [facebookresearch/pythia#15]
Ran the instructions at https://github.com/facebookresearch/pythia#docker-demo :

```
git clone https://github.com/facebookresearch/pythia.git
nvidia-docker build pythia -t pythia:latest
nvidia-docker run -ti --net=host pythia:latest
```

then loaded localhost:8888 in my web-browser. This showed a file listing containing 'vqa_demo' and 'vqa_standalone_image_demo'. Tried opening both of these, and doing 'restart and run all'. Both gave errors, though different errors:

vqa_demo:
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/imdb/imdb_test2015.npy'
```

vqa_standalone_image_demo:
```
FileNotFoundError: [Errno 2] No such file or directory: '/private/home/nvivek/VQA/pythia/vqa_detectron_master/config.yaml'
```

**Comment by apsdehal** [comment]
Try colab based demo, it shouldn't require to install anything. Closing for now. Reopen if issue persists.
