### ISSUE TITLE
Feature extract question

### ISSUE THREAD

**Issue by SelinaFelton** [facebookresearch/pythia#150]
## ❓ Questions and Help
I follow these steps to run extract_features_vmb.py: 
```
    1.Download the images to data/images, download model file and config file to data/
    2.Run python3 pythia/scripts/features/extract_features_vmb.py --image_dir data/images --model_file data/detectron_model.pth --config_file data/detectron_model.yaml
```
But I got:

> Segmentation fault (core dumped)
Have you ever met such a bug?

**Comment by apsdehal** [comment]
Memory issues probably. Check your memory size. Segmentation fault normally happen due to memory issues. You should on the side check output from htop and see if it reaches your memory limit when you run this command.

**Comment by SelinaFelton** [comment]
I have checked my memory, it's enough.

**Comment by apsdehal** [comment]
can you point to the exact image on which encountered the bug. I haven't seen it unless I am out of memory.

**Comment by gao-ye** [comment]
I use commond to process TextVQA dataset, the images are download from: [TextVQA](https://textvqa.org/)

>  CUDA_VISIBLE_DEVICES=7 python pythia/scripts/features/extract_features_vmb.py --image_dir data/TextVQA/train_images --model_file data/detectron_model.pth --config_file data/detectron_model.yaml

But I got Errors:

> Traceback (most recent call last):
> 
>   File "pythia/scripts/features/extract_features_vmb.py", line 235, in <module>
>     feature_extractor.extract_features()
>   File "pythia/scripts/features/extract_features_vmb.py", line 228, in extract_features
>     features, infos = self.get_detectron_features(chunk)
>   File "pythia/scripts/features/extract_features_vmb.py", line 184, in get_detectron_features
>     im, im_scale, im_info = self._image_transform(image_path)
>   File "pythia/scripts/features/extract_features_vmb.py", line 101, in _image_transform
>     im -= np.array([102.9801, 115.9465, 122.7717])
> ValueError: operands could not be broadcast together with shapes (1024,628,4) (3,) (1024,628,4)
>

**Comment by SelinaFelton** [comment]
> can you point to the exact image on which encountered the bug. I haven't seen it unless I am out of memory.

I tried 4 images in TextVQA dataset, all of them output Segmentation fault (core dumped), image_ids are:

> 0a1a9a99f177e69a, 0a2f1c772abd74b, 0a4c15b05648b4b2, 00a5dbacb0654efd 
Maybe any picture will be given such an error  in my enviorment

**Comment by gao-ye** [comment]
I guess this code process 2 images each time, my code stop at images:

> a2059d02bd44cd89.jpg and 3dfb039392e34ca2.jpg

**Comment by gao-ye** [comment]
> I use commond to process TextVQA dataset, the images are download from: [TextVQA](https://textvqa.org/)
> 
> > CUDA_VISIBLE_DEVICES=7 python pythia/scripts/features/extract_features_vmb.py --image_dir data/TextVQA/train_images --model_file data/detectron_model.pth --config_file data/detectron_model.yaml
> 
> But I got Errors:
> 
> > Traceback (most recent call last):
> > File "pythia/scripts/features/extract_features_vmb.py", line 235, in 
> > feature_extractor.extract_features()
> > File "pythia/scripts/features/extract_features_vmb.py", line 228, in extract_features
> > features, infos = self.get_detectron_features(chunk)
> > File "pythia/scripts/features/extract_features_vmb.py", line 184, in get_detectron_features
> > im, im_scale, im_info = self._image_transform(image_path)
> > File "pythia/scripts/features/extract_features_vmb.py", line 101, in _image_transform
> > im -= np.array([102.9801, 115.9465, 122.7717])
> > ValueError: operands could not be broadcast together with shapes (1024,628,4) (3,) (1024,628,4)

I guess this code process 2 images each time, my code stop at images:

> a2059d02bd44cd89.jpg and 3dfb039392e34ca2.jpg

**Comment by gao-ye** [comment]
I print the image path to check. 
When process test set of TextVQA, it also has errors and stop at:

> data/TextVQA/test_images/7409c167b0ea3ee8.jpg
data/TextVQA/test_images/78513e6212eb2887.jpg
Traceback (most recent call last):
  File "pythia/scripts/features/extract_features_vmb.py", line 236, in <module>
    feature_extractor.extract_features()
  File "pythia/scripts/features/extract_features_vmb.py", line 229, in extract_features
    features, infos = self.get_detectron_features(chunk)
  File "pythia/scripts/features/extract_features_vmb.py", line 185, in get_detectron_features
    im, im_scale, im_info = self._image_transform(image_path)
  File "pythia/scripts/features/extract_features_vmb.py", line 102, in _image_transform
    im -= np.array([102.9801, 115.9465, 122.7717])

**Comment by apsdehal** [comment]
I have encountered this bug locally. Some JPG images have four channels. For now patch it locally like this:

Replace `_image_transform` function with following code:
```
    def _image_transform(self, path):
        img = Image.open(path)
        im = np.array(img).astype(np.float32)

        if im.shape[-1] > 3:
            im = np.array(img.convert("RGB")).astype(np.float32)

        # IndexError: too many indices for array, grayscale images
        if len(im.shape) < 3:
            im = np.repeat(im[:, :, np.newaxis], 3, axis=2)

        im = im[:, :, ::-1]
        im -= np.array([102.9801, 115.9465, 122.7717])
        im_shape = im.shape
        im_height = im_shape[0]
        im_width = im_shape[1]
        im_size_min = np.min(im_shape[0:2])
        im_size_max = np.max(im_shape[0:2])

        # Scale based on minimum size
        im_scale = self.MIN_SIZE / im_size_min

        # Prevent the biggest axis from being more than max_size
        # If bigger, scale it down
        if np.round(im_scale * im_size_max) > self.MAX_SIZE:
            im_scale = self.MAX_SIZE / im_size_max

        im = cv2.resize(
            im, None, None, fx=im_scale, fy=im_scale, interpolation=cv2.INTER_LINEAR
        )
        img = torch.from_numpy(im).permute(2, 0, 1)

        im_info = {
            "width": im_width,
            "height": im_height
        }

        return img, im_scale, im_info
```

**Comment by liiiiiiiiil** [comment]
> I have encountered this bug locally. Some JPG images have four channels. For now patch it locally like this:
> 
> Replace `_image_transform` function with following code:
> 
> ```python
>     def _image_transform(self, path):
>         img = Image.open(path)
>         im = np.array(img).astype(np.float32)
> 
>         if im.shape[-1] > 3:
>             im = np.array(img.convert("RGB")).astype(np.float32)
> 
>         # IndexError: too many indices for array, grayscale images
>         if len(im.shape) < 3:
>             im = np.repeat(im[:, :, np.newaxis], 3, axis=2)
> 
>         im = im[:, :, ::-1]
>         im -= np.array([102.9801, 115.9465, 122.7717])
>         im_shape = im.shape
>         im_height = im_shape[0]
>         im_width = im_shape[1]
>         im_size_min = np.min(im_shape[0:2])
>         im_size_max = np.max(im_shape[0:2])
> 
>         # Scale based on minimum size
>         im_scale = self.MIN_SIZE / im_size_min
> 
>         # Prevent the biggest axis from being more than max_size
>         # If bigger, scale it down
>         if np.round(im_scale * im_size_max) > self.MAX_SIZE:
>             im_scale = self.MAX_SIZE / im_size_max
> 
>         im = cv2.resize(
>             im, None, None, fx=im_scale, fy=im_scale, interpolation=cv2.INTER_LINEAR
>         )
>         img = torch.from_numpy(im).permute(2, 0, 1)
> 
>         im_info = {
>             "width": im_width,
>             "height": im_height
>         }
> 
>         return img, im_scale, im_info
> ```

I met this bug too，and further more，this line code `files = glob.glob(os.path.join(image_dir, "*.jpg"))` shows that it can not handle some images like '1.JPEG'

**Comment by mineshmathew** [comment]
@apsdehal I have one question related to the feature extraction script using MaskRCNN benchmark. The script is running fine for me. I wanted to know how to modify the script or the model config file to run the inference on multi gpus ( data parallel) so that i can go for larger batch sizes) ?

**Comment by apsdehal** [comment]
You can try encapsulating it with DataParallel and see if it helps. Otherwise you can run multiple scripts by adapting `CUDA_VISIBLE_DEVICES` environment variable.

**Comment by apsdehal** [comment]
Also, I would suggest opening a new issue instead of spamming this one.
