### ISSUE TITLE
Error in executing train.py

### ISSUE THREAD

**Issue by ak-kat** [facebookresearch/pythia#154]
python3 train.py --config config/cycle_consistency/pythia_cycle_consistent.yml

unkown key:failure_predictor, in new config string 

Thanks in advance.

**Comment by apsdehal** [comment]
@meetshah1995 Can you look into this?

**Comment by ak-kat** [comment]
From here [https://github.com/facebookresearch/pythia/tree/project/cycle-consistency/config/cycle_consistency], when I am trying to execute train.py it is giving an error in:
**unkown key:failure_predictor, in new config string**

[(https://github.com/facebookresearch/pythia/blob/project/cycle-consistency/config/cycle_consistency/pythia_cycle_consistent.yml)]  (In line number 28)

CUDA_VISIBLE_DEVICES=0 python train.py --config config/cycle_consistency/pythia_cycle_consistent.yml

I hope I am clear now.

Thanks for your response.

**Comment by meetshah1995** [comment]
@ak-kat -- Are you cloning the `project/cycle-consistency` branch and running the code?

The cycle-consistency config (in the `project/cycle-consistency` branch) is from an older version of pythia and hence not usable with the `master` branch.

failure_predictor as you can see is a valid config option [here](https://github.com/facebookresearch/pythia/blob/project/cycle-consistency/config/config.py#L111)

**Comment by ak-kat** [comment]
Thanks.
So could you please tell how can I use cycle consistency code.
I will be thankful.

**Comment by apsdehal** [comment]
Inside pythia, run `git checkout project/cycle-consistency` and then run the commands.

**Comment by ak-kat** [comment]
Thanks.
