### ISSUE TITLE
Need more Info : Detectron Feature Info

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/pythia#156]
## ❓ Questions and Help
Hey,
I have been trying to understand the  _info data for  pre-extracted detectron features,
Inside the _info numpy file in addition to image width and height details and coordinates of the bounding boxes of 100 objects, I see two more fields -  object ( 100x 1 ) and cls_scores ( 100 x 2).

What do these fields contain/represent ?
 (I am not quite familiar with the object detection works,  please excuse)

**Comment by apsdehal** [comment]
Please ignore those for now. I will be uploading new features soon according to the current feature extraction script.
