### ISSUE TITLE
[docs] Merge README and Documentation

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/pythia#172]
Currently, there are two source of truth. One is readme and one is documentation. For each PR, we have to make sure both are consistent which is hard. There should be only one single source of truth. 

We should point to documentation from README for any getting started tutorial.

**Comment by Patil2099** [comment]
@apsdehal Can I work on it?

**Comment by apsdehal** [comment]
@Patil2099 Sure. Go ahead.

**Comment by pushkalkatara** [comment]
Hi @Patil2099 Are you working on this issue? 
@apsdehal If @Patil2099 iss not working on this issue, can i work on it?

I notice that README is the same as the [quickstart](https://learnpythia.readthedocs.io/en/latest/tutorials/quickstart.html) section of the documentation without the tables. What changes are to be made?

**Comment by apsdehal** [comment]
Plan is to keep only introduction and citation in README. Quickstart should point to documentation and there shouldn't be any other replication.

**Comment by pushkalkatara** [comment]
Hi, please find the PR here - https://github.com/facebookresearch/pythia/pull/189
