### ISSUE TITLE
Trying to train BUTD model with a different dataset

### ISSUE THREAD

**Issue by pidugusundeep** [facebookresearch/pythia#175]
## ❓ Questions and Help
I want to train the model with a different dataset altogether and I want to know how do I create the features set and `.npy` files for images and captions respectively?

**Comment by sarahallen111** [comment]
So for the captioning (at least what I did), was model my dataset to match COCO, since that was the dataset used for the BUTD model.

For the image database (imdb), I suggest downloading COCO's files to look at. Don't worry, the imdb files aren't very large. Then, you can see what the files look like opening up python and saying:

```
import numpy as np
data = np.load('imdb_karpathy_train.npy')
data_list = data.tolist()
```

Once you look at data_list, you can see that it's just a list of a bunch of dictionaries with the needed info in them. So, take your dataset, create that list of dictionaries, and then turn it back into a .npy file by saying something like:

`np.save('imdb_train.npy', new_database_list)`

For the feature set, what I used was the captioning demo (https://colab.research.google.com/drive/1vzrxDYB0vxtuUy8KCaGxm--nDCJvyBSg) and used the PythiaDemo class to get the features. Note that the path to the feature is a component of the imdb, so you (a) need a good naming system, and (b) probably should be saving your features at the same time you save your imdb. Also, you need to be doing the below for every single image in your database, so you'll have a lot of feature files.

Here's some sample code that can get you started:

```
#Get the pythia demo class object
demo = PythiaDemo()

#Extract the features
detectronFeatures = demo.get_detectron_features(/path/to/image/)
det_feature_array = np.asarray(detectronFeatures.cpu())

#Saving the features into the correct location
detName = (whatever your naming convention is)
np.save(detName, det_feature_array)
```

Finally, you need to make sure to change the equivalent of coco.yml for your dataset to make sure that the code knows where your imdb and feature files are.

**Comment by pidugusundeep** [comment]
Thanks a ton for spending your time, will try implementing the same.

**Comment by pidugusundeep** [comment]
Should i even generate the `vocabulary_captioning_thresh5.txt` file as well? or can I use the existing?

**Comment by sarahallen111** [comment]
You can use the existing, but if there are any words that are in the vocabulary of your dataset that aren't in `vocaulary_captioning_thresh5.txt` , then you should probably add them. I'm not sure what would happen if the trainer comes across a word it doesn't know... It might learn the meaning of the word, or it might just say it's an unknown (<unk>) and move on. So to be safe, add any extra words that you need to.

**Comment by apsdehal** [comment]
@sarahallen111 Thanks for explaining this in detail. 
@pidugusundeep   Some other things: for features, you can directly use the feature extraction script https://github.com/facebookresearch/pythia/blob/master/pythia/scripts/features/extract_features_vmb.py which uses vqa-maskrcnn-benchmark - same as what is used in the demo. 

For vocabulary, if some word is not inside your vocabulary, it will be converted to index of <unk> token, so you may want to add extra commonly occurring words to your vocabulary.

**Comment by apsdehal** [comment]
Also, a more detailed tutorial for adding your own dataset to pythia is available at https://learnpythia.readthedocs.io/en/latest/tutorials/dataset.html

**Comment by pidugusundeep** [comment]
@apsdehal Do I need a GPU to generate the feature set ??

**Comment by pidugusundeep** [comment]
@apsdehal Tried generating the features with https://github.com/facebookresearch/pythia/blob/master/pythia/scripts/features/extract_features_vmb.py but the resultant output directory is always empty

https://github.com/facebookresearch/pythia/blob/2df9160c6daa84830973a12a41f9109bc25e498d/pythia/scripts/features/extract_features_vmb.py#L89

Replaced this with `cpu`
As I am running the code on my local CPU machine.

**Comment by apsdehal** [comment]
It only picks up .jpg images. Make sure you have those in the folder. Can you upload set of some of your images somewhere so I can test?

**Comment by pidugusundeep** [comment]
I'm using this dataset for my training - https://github.com/facebookresearch/pythia/issues/175 I am trying to pick up `.png` files instead.

**Comment by pidugusundeep** [comment]
I somehow generated the .npy files with the script and now i have an issue with training it has an error 
`IndexError: index 52 is out of bounds for dimension 1 with size 52` do i need to have the note of the max number of words ?? in a caption or is it related to the vocab?

**Comment by pidugusundeep** [comment]
@sarahallen111 @apsdehal I have been using my own vocab file and that has less number of words when compared to the already existing 
```
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pythia_captioning_demo.py:113: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "pythia_captioning_demo.py", line 281, in <module>
    demo = PythiaDemo()
  File "pythia_captioning_demo.py", line 108, in __init__
    self.pythia_model = self._build_pythia_model()
  File "pythia_captioning_demo.py", line 147, in _build_pythia_model
    model.load_state_dict(state_dict)
  File "/home/u28740/PYTHIA3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BUTD:
	size mismatch for word_embedding.weight: copying a param with shape torch.Size([9491, 300]) from checkpoint, the shape in current model is torch.Size([2025, 300]).
	size mismatch for classifier.module.fc.bias: copying a param with shape torch.Size([9491]) from checkpoint, the shape in current model is torch.Size([2025]).
	size mismatch for classifier.module.fc.weight_g: copying a param with shape torch.Size([9491, 1]) from checkpoint, the shape in current model is torch.Size([2025, 1]).
	size mismatch for classifier.module.fc.weight_v: copying a param with shape torch.Size([9491, 1024]) from checkpoint, the shape in current model is torch.Size([2025, 1024]).
```
What exactly could be the issue here ?

**Comment by pidugusundeep** [comment]
> It only picks up .jpg images. Make sure you have those in the folder. Can you upload set of some of your images somewhere so I can test?

Earlier I was trying to use it from the demo script now changed it to .png and trying to generate the features

**Comment by apsdehal** [comment]
> @sarahallen111 @apsdehal I have been using my own vocab file and that has less number of words when compared to the already existing
> 
> ```
> You are using pip version 10.0.1, however version 19.2.3 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> pythia_captioning_demo.py:113: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   config = yaml.load(f)
> Traceback (most recent call last):
>   File "pythia_captioning_demo.py", line 281, in <module>
>     demo = PythiaDemo()
>   File "pythia_captioning_demo.py", line 108, in __init__
>     self.pythia_model = self._build_pythia_model()
>   File "pythia_captioning_demo.py", line 147, in _build_pythia_model
>     model.load_state_dict(state_dict)
>   File "/home/u28740/PYTHIA3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for BUTD:
> 	size mismatch for word_embedding.weight: copying a param with shape torch.Size([9491, 300]) from checkpoint, the shape in current model is torch.Size([2025, 300]).
> 	size mismatch for classifier.module.fc.bias: copying a param with shape torch.Size([9491]) from checkpoint, the shape in current model is torch.Size([2025]).
> 	size mismatch for classifier.module.fc.weight_g: copying a param with shape torch.Size([9491, 1]) from checkpoint, the shape in current model is torch.Size([2025, 1]).
> 	size mismatch for classifier.module.fc.weight_v: copying a param with shape torch.Size([9491, 1024]) from checkpoint, the shape in current model is torch.Size([2025, 1024]).
> ```
> 
> What exactly could be the issue here ?

The error here is clear, you are trying to load a pretrain model with different word embedding size into your model. So it won't work.

**Comment by manavkhothari** [comment]
> @apsdehal Tried generating the features with https://github.com/facebookresearch/pythia/blob/master/pythia/scripts/features/extract_features_vmb.py but the resultant output directory is always empty
> 
> https://github.com/facebookresearch/pythia/blob/2df9160c6daa84830973a12a41f9109bc25e498d/pythia/scripts/features/extract_features_vmb.py#L89
> 
> Replaced this with `cpu`
> As I am running the code on my local CPU machine.
> 
> This is my command for execution
> 
> ```
> python extract_features_vmb.py 
>     --config_file pythia/pythia/scripts/features/detectron_model.yaml  
>     --model_file pythia/pythia/scripts/features/detectron_model.pth 
>     --output_folder Xray/results 
>     --image_dir Xray/NLMCXR 
>     --num_features 100
> ```

Hi @pidugusundeep @apsdehal 
I have been trying this method on my local system, but the output file is empty.
I'm not able to solve this error. Can you guide me towards the solution ?
