### ISSUE TITLE
Question about OCR info

### ISSUE THREAD

**Issue by xinke-wang** [facebookresearch/pythia#176]
## ❓ Questions and Help

Hi, thanks for the work. I noticed that the textVQA imdb provides ocr results obtained by the rosetta system, which includes both ocr tokens and their position. The format of the ocr token position is defined as ['top_left_x', 'top_left_y', 'width', 'height', 'rotation', 'yaw', 'roll', 'pitch']. 

However, I found that the 'build_bbox_tensors' function in pythia/utils/dataset_utils.py only uses x, y, w and h to get the bounding boxes, which can not correctly handle the rotated rectangles. Could you tell me how can I use the rest parameters, i.e., 'rotation', 'yaw', 'roll' and 'pitch' to obtain the correct rectangle positions? something like [x1, y1, x2, y2, x3, y3, x4, y4].

Thank you very much.

**Comment by apsdehal** [comment]
In general, you can update the processor to handle rotation. But, in whatever experiments I conducted I passed rest of them as features, because some of them are 3d transforms.
