### ISSUE TITLE
[Question] Using GloVE for word tokens in the Question

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/pythia#178]
## ❓ Questions and Help
For LoRRA it is mentioned that GloVe embeddings are used to first represent the individual tokens and then the sequence of tokens are encoded using a bi-RNN to represent the entire question.

But while reading the code what I understand is that the text tokens are first converted to integer indices based on a vocabulary and then used  with an nn.Embedding layer. I suppose the GloVe embeddings are used to initialize the weights of this embedding layer. But I am unable to figure where/how this is done. I don't see any pre-trained weights files for Glove being used anywhere in the code.
Please excuse if what I am asking is quite obvious

**Comment by apsdehal** [comment]
See this line: https://github.com/facebookresearch/pythia/blob/master/pythia/models/pythia.py#L36. It takes embedding's weight based on text processor's vocab which is set to glove by default in textvqa. https://github.com/facebookresearch/pythia/blob/2c911a32b0f8d4f9169444d18f2999461ab51d57/pythia/common/defaults/configs/tasks/vqa/textvqa.yml#L27

**Comment by mineshmathew** [comment]
Thank you.
So the pretrained glove vectors are loaded at this step
https://github.com/facebookresearch/pythia/blob/master/pythia/utils/vocab.py#L191 right?

If that is the case I was wondering why is there are a GloveProcessor class in https://github.com/facebookresearch/pythia/blob/master/pythia/tasks/processors.py

I dont see it being used anywhere.

**Comment by apsdehal** [comment]
Yes, you are right about the line.

I don't think we use GloVeProcessor anywhere as of now. But it is present in case you want to load embeddings before hand similar to how we do it with FastTextProcessor.
