### ISSUE TITLE
extract features error

### ISSUE THREAD

**Issue by lecidhugo** [facebookresearch/pythia#179]
## ❓ Questions and Help
Hi,
I tried extract_features.py as described in: 
https://github.com/facebookresearch/pythia/blob/master/pythia/scripts/features/extract_features.md

python extract_features.py --cfg e2e_faster_rcnn_X-101-64x4d-FPN_1x_MLP_2048_FPN_512.yaml \
--wts FAST_RCNN_MLP_DIM2048_FPN_DIM512.pkl \
--min_bboxes 100 --max_bboxes 100 \
--feat_name gpu_0/fc6 \
--output_dir ~/temp_out $INPUT_DIR

However, I got the following error:
Traceback (most recent call last):
  File "extract_features.py", line 312, in <module>
    main(args)
  File "extract_features.py", line 246, in main
    model = infer_engine.initialize_model_from_cfg(args.weights)
  File "/workspace/Detectron/detectron/core/test_engine.py", line 327, in initialize_model_from_cfg
    model = model_builder.create(cfg.MODEL.TYPE, train=False, gpu_id=gpu_id)
  File "/workspace/Detectron/detectron/modeling/model_builder.py", line 120, in create
    init_params=train
  File "/workspace/Detectron/detectron/modeling/detector.py", line 49, in __init__
    assert self.num_classes > 0, 'num_classes must be > 0'
AssertionError: num_classes must be > 0

Any help ?
Thanks in advance,

**Comment by apsdehal** [comment]
Which commit are you using? 

Also, can you use https://github.com/facebookresearch/pythia/blob/master/pythia/scripts/features/extract_features_vmb.py to extract features. You will need to install [vqa-maskrcnn-benchmark](https://gitlab.com/meetshah1995/vqa-maskrcnn-benchmark/) first.

**Comment by lecidhugo** [comment]
Thank you @apsdehal,
In fact I used a prebuilt Detectron docker image (https://hub.docker.com/r/housebw/detectron). I run extract_features.py from inside the container. I do not know which commit has been used to build the image.
So, you propose that I use vqa-maskrcnn-benchmark instead of Detectron?

**Comment by apsdehal** [comment]
As mentioned in the README for extracting features, you need a specific commit of Caffe2 and Detectron. It won't work without that. 

I would recommend using the extract_features_vmb.py script because we will be mostly supporting that one in future.
