### ISSUE TITLE
Adding mirror data make the training worse

### ISSUE THREAD

**Issue by gaopeng-eugene** [facebookresearch/pythia#18]
data:
  batch_size: 512
  data_root_dir: data
  dataset: vqa_2.0
  image_depth_first: false
  image_fast_reader: false
  image_feat_test:
  - detectron_fix_100/fc6/vqa/val2014/
  image_feat_train:
  - detectron_fix_100/fc6/vqa/train2014/
  - detectron_fix_100/fc6/vqa_mirror/train2014
  image_feat_val:
  - detectron_fix_100/fc6/vqa/val2014/
  image_max_loc: 100
  imdb_file_test:
  - imdb/imdb_minival2014.npy
  imdb_file_train:
  - imdb/imdb_train2014.npy
  - imdb/imdb_mirror_train2014.npy
  imdb_file_val:
  - imdb/imdb_val2014.npy
  num_workers: 20
  question_max_len: 14
  vocab_answer_file: answers_vqa.txt
  vocab_question_file: vocabulary_vqa.txt
exp_name: intrainter_baseline

Hi, when I add the mirror data of training into training. The performance drop a lot for validation. 
Do you have any suggestion?

**Comment by YuJiang01** [comment]
when adding mirror data, the learning schedule also need to be adjusted. you can try our config file, which is included in https://s3-us-west-1.amazonaws.com/pythia-vqa/pretrained_models/most_data.tar.gz
