### ISSUE TITLE
Does CLEVR features extracted from detectron? 

### ISSUE THREAD

**Issue by idansc** [facebookresearch/pythia#183]
## ❓ Questions and Help
The README is a bit confusing.

**Comment by apsdehal** [comment]
We don't have extracted out features for CLEVR. Our supported model for now is CNNLSTM which uses a CNN architecture to extract out features for the image on the fly. If you want to extract out features using detectron, you will have to do it at your end using feature extraction scripts we have.

**Comment by apsdehal** [comment]
Alternatively, you can use pretrained models from torchvision for extracting out features on the fly.
