### ISSUE TITLE
TextVQA challenge question

### ISSUE THREAD

**Issue by SelinaFelton** [facebookresearch/pythia#184]
## ❓ Questions and Help
I followed the step of `https://learnpythia.readthedocs.io/en/latest/tutorials/challenge.html` to submit my result, but when I go in ‘My submissions’ section and click on ‘Result file’ to check your results, the result always is 'None'.

**Comment by apsdehal** [comment]
I have pointed this out to evalai folks. Once they get back to me, I will provide an update to you.

**Comment by apsdehal** [comment]
Should be fixed now. Let me know if the issue persists.

**Comment by apsdehal** [comment]
Going to close this. Let us know if there is some other issue.
