### ISSUE TITLE
About the size of fc6

### ISSUE THREAD

**Issue by dandelin** [facebookresearch/pythia#19]
In the paper, you've mentioned that 

> This allows us to extract the 2048D fc6 features ...

As far as I know, Detectron's original FPN 2MLP head uses 1024D as channel dim. (https://github.com/facebookresearch/Detectron/blob/master/detectron/core/config.py#L643)

Is there any reason you chose 2048D over 1024D? Will there be any performance degrading (mAP for genome or acc for VQA) for using 1024D feature?

Thanks!

**Comment by YuJiang01** [comment]
we tried both 1024D and 2048D and found that using 2048D has better VQA performance
