### ISSUE TITLE
maskrcnn-benchmark is still needed for feature extraction?

### ISSUE THREAD

**Issue by ggaemo** [facebookresearch/pythia#193]
## ❓ Questions and Help
In the demo, it requires maskrcnn-benchmark from the repository of meetshah1995. 
Why is the repository not https://github.com/facebookresearch/maskrcnn-benchmark

also, is the detection model part not moving the detectron2? The maskrcnn-benchmark repository shows that the repository is deprecated

**Comment by apsdehal** [comment]
We have a custom fork of maskrcnn- benchmark which introduces attribute based loss from visual genome. We currently don't have plans to move to detectron2 as someone with dedicated cycles is needed to perform the migration due to breaking changes.
