### ISSUE TITLE
cls_score of the detectron model

### ISSUE THREAD

**Issue by ggaemo** [facebookresearch/pythia#194]
## ❓ Questions and Help
The cls_score of the detectron model has 1601 outputs, not 1600.

Does the first column correspond to the objectness score that the RPN outputs?
Or is it separately trained to differentiate between being a background and an object?

Also, are the scores per class? or is it in softmax?

**Comment by ggaemo** [comment]
I got the answer from _process_feature_extraction function in the feature extraction file.

It puts the softmax across all the 1601 categories.

Does this mean that there is a separate class for backgrounds in the visual genome dataset? Is it present in the original VG dataset? Or is it made specifically for pythia?

**Comment by apsdehal** [comment]
No, anything that doesn't have enough IoU with any boxes is considered background.
