### ISSUE TITLE
Feature Bounding Boxes don't match to image

### ISSUE THREAD

**Issue by PaulOpu** [facebookresearch/pythia#196]
## ❓ Questions and Help
I extracted the bounding boxes of the resnet152 features from the `pythia/data/open_images/detectron_fix_100/fc6/train/{image_name}_info.npy` file and tried to visualize the bounding boxes on the image. 

```
boxes = np.zeros((100,5))
boxes[:,:-1] = image_dic["boxes"]
boxes[:,4] = image_dic["cls_scores"]

from pythia.legacy.tools.visualize_bbox import vis_detections
img = load_image_from_url(orig_image_url)
vis_detections(img,class_name,[],boxes,thresh=0.8)
```

1e4fcfbd0bb6e1e1
![image](https://user-images.githubusercontent.com/22904585/68468204-d63c4980-0217-11ea-83bd-26066fd22230.png)

Unfortunately, the mapped objects didn't seem to match with the image (at least I don't see a connection). That happens for the original image (flickr_original_url) and the cropped one (flickr_300k_url), validated with many images. 

Is there something I do wrong? Thank you for your help!

**Comment by michaelroyzen** [comment]
I may be having this issue as well. How did you solve it?

**Comment by Ra0k** [comment]
@PaulOpu how did you extract the bounding boxes?

**Comment by PaulOpu** [comment]
You need to resize the image first to the dimensions of the image with which the bboxes were created. Resize your image to "image_h" and "image_w" in the detectron image "..._info.npy" and use that as your img.
