### ISSUE TITLE
how to train a new data set on the pre-training model?

### ISSUE THREAD

**Issue by cylvzj** [facebookresearch/pythia#197]
If you want to add a new dataset (possibly with new vocabulary), do you need to restart the training model pair?

Is it possible to make answer_vqa.txt and vocabulary_100k.txt as large as possible (including all vocabulary as much as possible) so that you don't have to worry about adding new vocabulary when adding a dataset. So you can train new data sets on pre-trained models?

I use demos (Pythia VQA, BUTD Captioning.) in colab (11G memory). It takes about 6 seconds to return the result. What kind of GPU configuration is needed, so that the result can be returned in 1-2 seconds?

**Comment by apsdehal** [comment]
Hi,
Let's please continue the discussion on the original issue so the information doesn't get defragmented for future readers. (Also, it is better to wait for some time for my reply. I will eventually reply but sometime it is late as I might be traveling etc.).

Closing as question has already been asked at #195.
