### ISSUE TITLE
ImportError: cannot import name 'load_model'

### ISSUE THREAD

**Issue by Thalaivar** [facebookresearch/pythia#205]
## ❓ Questions and Help
While training LoRRA on TextVQA, after a certain number of iterations, the code always runs into an error with fastText:

File "/content/pythia/pythia/tasks/processors.py", line 460, in _load_fasttext_model
    from fastText import load_model
ImportError: cannot import name 'load_model'

**Comment by apsdehal** [comment]
Can you replace `fastText` with `fasttext`? This will be fixed in next release. This is happening due to recent update to `fasttext` library.
