### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for LoRRA

### ISSUE THREAD

**Issue by akasharidas** [facebookresearch/pythia#207]
Hi, I am trying to run inference on the VizWiz dataset using the pretrained model of LoRRA. 

I run this: `python tools/run.py --tasks vqa --datasets vizwiz --model lorra --config configs/vqa/vizwiz/lorra.yml --run_type val --num_workers 0 --resume_file data/models/lorra_best.pth`

I get the following error while it tries to load a checkpoint.

`Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 82, in run
    trainer.load()
  File "/content/pythia/pythia/trainers/base_trainer.py", line 48, in load
    self.load_extras()
  File "/content/pythia/pythia/trainers/base_trainer.py", line 169, in load_extras
    self.checkpoint.load_state_dict()
  File "/content/pythia/pythia/utils/checkpoint.py", line 63, in load_state_dict
    self._load(tp.resume_file)
  File "/content/pythia/pythia/utils/checkpoint.py", line 114, in _load
    self.trainer.model.load_state_dict(final_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for LoRRA:
	size mismatch for classifier.module.linear_text.weight: copying a param with shape torch.Size([4047, 300]) from checkpoint, the shape in current model is torch.Size([7421, 300]).
	size mismatch for classifier.module.linear_text.bias: copying a param with shape torch.Size([4047]) from checkpoint, the shape in current model is torch.Size([7421]).
	size mismatch for classifier.module.linear_image.weight: copying a param with shape torch.Size([4047, 5000]) from checkpoint, the shape in current model is torch.Size([7421, 5000]).
	size mismatch for classifier.module.linear_image.bias: copying a param with shape torch.Size([4047]) from checkpoint, the shape in current model is torch.Size([7421]). `

Please help me with this!

**Comment by apsdehal** [comment]
LoRRA's pretrained model isn't supposed to be run on VizWiz as both have different answer space. You can technically run it on VizWiz by changing the answer space of VizWiz to be same as that of TextVQA by replacing line https://github.com/facebookresearch/pythia/blob/master/pythia/common/defaults/configs/tasks/vqa/vizwiz.yml#L41 to `vocab_file: vocabs/answers_textvqa_more_than_1.txt`.

I would rather suggest to retrain a LoRRA model on VizWiz.

**Comment by akasharidas** [comment]
I changed the line, but it is still showing the same error. It seems to have something to do with the dimensions of the final Linear layer.

> I would rather suggest to retrain a LoRRA model on VizWiz.

I was trying to use the pre-trained model as a starting point for training, since both textVQA and VizWiz are VQA tasks. Can I not do this?

**Comment by apsdehal** [comment]
I see, actually you have to change this line https://github.com/facebookresearch/pythia/blob/master/configs/vqa/vizwiz/lorra.yml#L13. Try this one it should work.

> I was trying to use the pre-trained model as a starting point for training, since both textVQA and VizWiz are VQA tasks. Can I not do this?

You can, add `--load_pretrained 1` to you arguments. See https://github.com/facebookresearch/pythia/blob/master/pythia/utils/flags.py#L198 for its explanation.

**Comment by akasharidas** [comment]
That worked, thank you very much for your quick reply :)
