### ISSUE TITLE
BUTD inference

### ISSUE THREAD

**Issue by michaelroyzen** [facebookresearch/pythia#216]
## ❓ Questions and Help
I'm new to Pytorch. For some reason, Pythia saves checkpoints as .ckpt instead of .pth. I'm trying to do inference with BUTD model I trained: 
`python tools/run.py --tasks captioning --datasets coco --model butd --config \
configs/captioning/coco/butd_beam_search.yml --resume_file save/captioning_coco_butd/best.ckpt \
--evalai_inference 1 --run_type inference`

I get this error: `RuntimeError: Error(s) in loading state_dict for BUTD:
        Missing key(s) in state_dict: "word_embedding.weight", "image_feature_encoders.0.module.lc.weight", "image_feature_encoders.0.module.lc.bias", "image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_image.bias", "image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_image.weight_g", "image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_image.weight_v", "image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_hidden.bias", "image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_hidden.weight_g", "image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_hidden.weight_v", "image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.top_down_lstm.weight_ih", "image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.top_down_lstm.weight_hh", "image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.top_down_lstm.bias_ih", "image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.top_down_lstm.bias_hh", "image_feature_embeddings_list.0.0.image_attention_model.module.transform.module.lc.bias", "image_feature_embeddings_list.0.0.image_attention_model.module.transform.module.lc.weight_g", "image_feature_embeddings_list.0.0.image_attention_model.module.transform.module.lc.weight_v", "classifier.module.language_lstm.weight_ih", "classifier.module.language_lstm.weight_hh", "classifier.module.language_lstm.bias_ih", "classifier.module.language_lstm.bias_hh", "classifier.module.fc.bias", "classifier.module.fc.weight_g", "classifier.module.fc.weight_v". 
        Unexpected key(s) in state_dict: "module.word_embedding.weight", "module.image_feature_encoders.0.module.lc.weight", "module.image_feature_encoders.0.module.lc.bias", "module.image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_image.bias", "module.image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_image.weight_g", "module.image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_image.weight_v", "module.image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_hidden.bias", "module.image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_hidden.weight_g", "module.image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.fa_hidden.weight_v", "module.image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.top_down_lstm.weight_ih", "module.image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.top_down_lstm.weight_hh", "module.image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.top_down_lstm.bias_ih", "module.image_feature_embeddings_list.0.0.image_attention_model.module.combination_layer.module.top_down_lstm.bias_hh", "module.image_feature_embeddings_list.0.0.image_attention_model.module.transform.module.lc.bias", "module.image_feature_embeddings_list.0.0.image_attention_model.module.transform.module.lc.weight_g", "module.image_feature_embeddings_list.0.0.image_attention_model.module.transform.module.lc.weight_v", "module.classifier.module.language_lstm.weight_ih", "module.classifier.module.language_lstm.weight_hh", "module.classifier.module.language_lstm.bias_ih", "module.classifier.module.language_lstm.bias_hh", "module.classifier.module.fc.bias", "module.classifier.module.fc.weight_g", "module.classifier.module.fc.weight_v". `

Please help me properly perform inference on a BUTD model I trained. How do I convert the .ckpt files to .pth?

**Comment by michaelroyzen** [comment]
Fixed; a .pth file is generated at end of training.

**Comment by apsdehal** [comment]
For future reference, ckpt has a "model" attribute which contains the model's state dict.
