### ISSUE TITLE
Why do we we need to split config['data']['image_feat_train'][0]?

### ISSUE THREAD

**Issue by curry111** [facebookresearch/pythia#22]
In `train_model/helper.py`    

```
> num_image_feat = len(config['data']['image_feat_train'][0].split(','))
```
although in `config` there is
`__C.data.image_feat_train = ["rcnn_10_100/vqa/train2014",
                             "rcnn_10_100/vqa/val2014"]`
So `config['data']['image_feat_train'][0]` is equal `"rcnn_10_100/vqa/train2014"`.
Why do we need to split that string using `.split(',')`?

Also, what does this if-condition mean?

```
> if hasattr(my_model, 'module'):
>    model = my_model.module
```
This if-condition is false(I mean `hasattr(my_model, 'module')` is false. But I don't know what those two lines mean.      
Thank you so much for answering my last two questions by the way :blush: your code and your paper are great guides for me :relaxed:

**Comment by YuJiang01** [comment]
`> num_image_feat = len(config['data']['image_feat_train'][0].split(','))`
This is used to allow multiple features, for example, object level feature and grid level feature, they are separated with ','
`> if hasattr(my_model, 'module'):
>    model = my_model.module`
This is because the module is passes to GPU

**Comment by curry111** [comment]
@YuJiang01 I am sorry of opening this issue again but 
In `train_model/model_factory.py`
There is this code (which sends the model to the GPU)
```
> if use_cuda:
>     my_model = my_model.cuda()
```
On the other hands, in
```
> if hasattr(my_model, 'module'):
>    model = my_model.module
```
What do you mean by  "because the module is passed to GPU" :sweat_smile: . This condition `hasattr(my_model, 'module')` is false. I mean if you wrote a print statement inside the if-condition it won't be executed.
Even afterwards in the code when we train the model using the function `one_stage_train`, we don't pass the "model" variable, we pass "my_model".  What do those 2 lines do? 
PS : I am using pytorch 4.0 not 3 as you used in this project, Is that an issue? 
I am sorry if this issue is really easy :sweat_smile: maybe my coding skills using pytorch are not that great.
