### ISSUE TITLE
Quickstart for image captioning - Tensors must have same number of dimensions: got 2 and 3

### ISSUE THREAD

**Issue by cylvzj** [facebookresearch/pythia#224]
Hello, when training captioning, the following error is prompted. With reference to #203, butd.py is up-to-date. Please ask,  how to solve it?

torch.cat([h2, image_feat_mean, embedding], dim=1), (h1, c1)

h2.ndim=2, image_feat_mean.ndim=3, embedding.ndim=2

(the entire Pythia master code was just downloaded, but the dataset was downloaded earlier.)

The error is as follows:

python3  tools/run.py --tasks captioning --datasets coco --model butd --config  configs/captioning/coco/butd.yml
Logging to: ./save/captioning_coco_butd/logs/captioning_coco_butd_2020-02-09T11:56:34.log
2020-02-09T11:56:34 INFO: =====  Training Parameters    =====
2020-02-09T11:56:34 INFO: {
    "batch_size": 256,
    "clip_gradients": true,
    "clip_norm_mode": "all",
    "data_parallel": false,
    "device": "cuda",
    "distributed": false,
    "evalai_inference": false,
    "experiment_name": "run",
    "load_pretrained": false,
    "local_rank": null,
    "log_dir": "./logs",
    "log_interval": 100,
    "logger_level": "info",
    "lr_ratio": 0.1,
    "lr_scheduler": true,
    "lr_steps": [
        15000,
        25000,
        35000,
        45000
    ],
    "max_epochs": null,
    "max_grad_l2_norm": 0.25,
    "max_iterations": 50000,
    "metric_minimize": false,
    "monitored_metric": "caption_bleu4",
    "num_workers": 7,
    "patience": 4000,
    "pin_memory": false,
    "pretrained_mapping": {},
    "resume": false,
    "resume_file": null,
    "run_type": "train+inference",
    "save_dir": "./save",
    "seed": null,
    "should_early_stop": false,
    "should_not_log": false,
    "snapshot_interval": 1000,
    "task_size_proportional_sampling": true,
    "trainer": "base_trainer",
    "use_warmup": true,
    "verbose_dump": false,
    "warmup_factor": 0.2,
    "warmup_iterations": 1000
}
2020-02-09T11:56:34 INFO: ======  Task Attributes  ======
2020-02-09T11:56:34 INFO: ======== captioning/coco =======
2020-02-09T11:56:34 INFO: {
    "data_root_dir": "../data",
    "fast_read": false,
    "features_max_len": 100,
    "image_depth_first": false,
    "image_features": {
        "test": [
            "coco/detectron_fix_100/fc6/train_val_2014"
        ],
        "train": [
            "coco/detectron_fix_100/fc6/train_val_2014"
        ],
        "val": [
            "coco/detectron_fix_100/fc6/train_val_2014"
        ]
    },
    "imdb_files": {
        "test": [
            "imdb/coco_captions/imdb_karpathy_test.npy"
        ],
        "train": [
            "imdb/coco_captions/imdb_karpathy_train.npy"
        ],
        "val": [
            "imdb/coco_captions/imdb_karpathy_val.npy"
        ]
    },
    "min_captions_per_img": 5,
    "processors": {
        "caption_processor": {
            "params": {
                "vocab": {
                    "embedding_name": "glove.6B.300d",
                    "type": "intersected",
                    "vocab_file": "vocabs/vocabulary_captioning_thresh5.txt"
                }
            },
            "type": "caption"
        },
        "text_processor": {
            "params": {
                "max_length": 52,
                "preprocessor": {
                    "params": {},
                    "type": "simple_sentence"
                },
                "vocab": {
                    "embedding_name": "glove.6B.300d",
                    "type": "intersected",
                    "vocab_file": "vocabs/vocabulary_captioning_thresh5.txt"
                }
            },
            "type": "vocab"
        }
    },
    "return_info": false,
    "use_ocr": false,
    "use_ocr_info": false
}
2020-02-09T11:56:34 INFO: ======  Optimizer Attributes  ======
2020-02-09T11:56:34 INFO: {
    "params": {
        "eps": 1e-08,
        "lr": 0.01,
        "weight_decay": 0
    },
    "type": "Adamax"
}
2020-02-09T11:56:34 INFO: ======  Model (butd) Attributes  ======
2020-02-09T11:56:34 INFO: {
    "classifier": {
        "params": {
            "dropout": 0.5,
            "fc_bias_init": 0,
            "feature_dim": 2048,
            "hidden_dim": 1024
        },
        "type": "language_decoder"
    },
    "embedding_dim": 300,
    "image_feature_dim": 2048,
    "image_feature_embeddings": [
        {
            "modal_combine": {
                "params": {
                    "attention_dim": 1024,
                    "dropout": 0.5,
                    "hidden_dim": 1024
                },
                "type": "top_down_attention_lstm"
            },
            "normalization": "softmax",
            "transform": {
                "params": {
                    "out_dim": 1
                },
                "type": "linear"
            }
        }
    ],
    "image_feature_encodings": [
        {
            "params": {
                "bias_file": "detectron/fc6/fc7_b.pkl",
                "weights_file": "detectron/fc6/fc7_w.pkl"
            },
            "type": "finetune_faster_rcnn_fpn_fc7"
        }
    ],
    "inference": {
        "params": {
            "beam_length": 1
        },
        "type": "beam_search"
    },
    "losses": [
        {
            "type": "caption_cross_entropy"
        }
    ],
    "metrics": [
        {
            "type": "caption_bleu4"
        }
    ],
    "model_data_dir": "../data/"
}
2020-02-09T11:56:34 INFO: Loading tasks and data
2020-02-09T11:56:40 INFO: CUDA Device 0 is: Tesla P40
2020-02-09T11:56:44 INFO: Torch version is: 1.1.0
2020-02-09T11:56:44 INFO: ===== Model =====
2020-02-09T11:56:44 INFO: BUTD(
  (word_embedding): Embedding(9535, 300)
  (image_feature_encoders): ModuleList(
    (0): ImageEncoder(
      (module): FinetuneFasterRcnnFpnFc7(
        (lc): Linear(in_features=2048, out_features=2048, bias=True)
      )
    )
  )
  (image_feature_embeddings_list): ModuleList(
    (0): ModuleList(
      (0): ImageEmbedding(
        (image_attention_model): AttentionLayer(
          (module): TopDownAttention(
            (combination_layer): ModalCombineLayer(
              (module): TopDownAttentionLSTM(
                (fa_image): Linear(in_features=2048, out_features=1024, bias=True)
                (fa_hidden): Linear(in_features=1024, out_features=1024, bias=True)
                (top_down_lstm): LSTMCell(3372, 1024)
                (relu): ReLU()
                (dropout): Dropout(p=0.5)
              )
            )
            (transform): TransformLayer(
              (module): LinearTransform(
                (lc): Linear(in_features=1024, out_features=1, bias=True)
              )
            )
          )
        )
      )
    )
  )
  (classifier): ClassifierLayer(
    (module): LanguageDecoder(
      (language_lstm): LSTMCell(3072, 1024)
      (fc): Linear(in_features=1024, out_features=9535, bias=True)
      (dropout): Dropout(p=0.5)
    )
  )
  (losses): Losses()
)
2020-02-09T11:56:44 INFO: Starting training...
2020-02-09T11:57:03 ERROR: invalid argument 0: Tensors must have same number of dimensions: got 2 and 3 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:62
Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 83, in run
    trainer.train()
  File "/home/dc2-user/content/pythia/pythia/trainers/base_trainer.py", line 239, in train
    report = self._forward_pass(batch)
  File "/home/dc2-user/content/pythia/pythia/trainers/base_trainer.py", line 259, in _forward_pass
    model_output = self.model(prepared_batch)
  File "/home/dc2-user/content/pythia/pythia/models/base_model.py", line 120, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dc2-user/content/pythia/pythia/models/butd.py", line 140, in forward
    "image", sample_list, embedding[:, 0, :], batch_size_t=batch_size_t
  File "/home/dc2-user/content/pythia/pythia/models/pythia.py", line 262, in process_feature_embedding
    embedding, attention = feature_embedding_model(*inp)
  File "/usr/local/python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dc2-user/content/pythia/pythia/modules/embeddings.py", line 206, in forward
    image_feat_variable, question_embedding, image_dims
  File "/usr/local/python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dc2-user/content/pythia/pythia/modules/attention.py", line 34, in forward
    return self.module(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dc2-user/content/pythia/pythia/modules/attention.py", line 138, in forward
    joint_feature = self.combination_layer(image_feat, question_embedding)
  File "/usr/local/python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dc2-user/content/pythia/pythia/modules/layers.py", line 182, in forward
    return self.module(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dc2-user/content/pythia/pythia/modules/layers.py", line 349, in forward
    torch.cat([h2, image_feat_mean, embedding], dim=1), (h1, c1)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 2 and 3 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:62

**Comment by cylvzj** [comment]
@vedanuj

**Comment by cylvzj** [comment]
Here common/sample.py ndim starts to equal 3， adding a len(samples)。

        for field in fields:
            if isinstance(samples[0][field], torch.Tensor):
                ==【size = (len(samples), *samples[0][field].size())】==
                self[field] = samples[0][field].new_empty(size)
                if self._get_tensor_field() is None:
                    self._set_tensor_field(field)
            else:
                self[field] = [None for _ in range(len(samples))]

Asking for help

**Comment by vedanuj** [comment]
In `configs/captioning/coco/butd.yml` can you remove 

```
      type: beam_search
      params:
        beam_length: 1
```

and replace with : 

```
      type: greedy
```

Let me know if that works.

**Comment by cylvzj** [comment]
Thank you！
There are no more mistakes. What's the difference between beam_search and greedy？

**Comment by cylvzj** [comment]
@vedanuj 

Hello,

During the training, I need to set type: greedy. After the training, when I call the model, I need to set type : beam_search, right? I tried. If it's always type:greedy, there will be an error when I call it.

**Comment by vedanuj** [comment]
During inference you should set type to beam_search. We will fix the training script soon to use greedy only.

**Comment by cylvzj** [comment]
Thank you for reply.

**Comment by cylvzj** [comment]
请问一下， 怎样减少奖励权重 （reduce the weight of the concept reward）?

**Comment by cylvzj** [comment]
请问一下， 怎样减少奖励权重 （reduce the weight of the concept reward）?
