### ISSUE TITLE
coco.tar.gz， How to view the pictures inside?

### ISSUE THREAD

**Issue by cylvzj** [facebookresearch/pythia#225]
## ❓ Questions and Help

It's all files like this. How to view the pictures?

detectron_fix_100/fc6/train_val_2014/COCO_train2014_000000560604.npy

**Comment by vedanuj** [comment]
Hi .. these are not the pictures but extracted features. You can download the images from the VQA website https://visualqa.org/download.html

**Comment by cylvzj** [comment]
Thank you for reply.

**Comment by cylvzj** [comment]
请问一下， 怎样减少奖励权重 （reduce the weight of the concept reward）?
