### ISSUE TITLE
Output Image Captioning Confidence Values

### ISSUE THREAD

**Issue by yutaroyamanaka** [facebookresearch/pythia#227]
## ❓ Questions and Help

Hello, I am a beginner of captioning and vqa.
I am running a notebook(https://colab.research.google.com/drive/1vzrxDYB0vxtuUy8KCaGxm--nDCJvyBSg) 

The last cell in the notebook says that "Image URL can be any http/https URL. We show top 5 predictions from Pythia. Confidence shows how confident Pythia model was about a particular prediction." as attached picture shows, but there are no confidence outputs.

I don't know whether it is possible to output confidence values in captioning tasks.
I'll be glad if you tell me the answer or code.
Thank you
<img width="1186" alt="スクリーンショット 2020-02-29 12 56 04" src="https://user-images.githubusercontent.com/34850155/75600499-54886880-5af3-11ea-9a25-16e61eb83cb9.png">

**Comment by apsdehal** [comment]
It is not directly possible because captioning is a generation task but you can multiply each generated word's probability to get a sense of overall confidence. Again, as this will penalize longer strings, I won't recommend using this as a strong signal.

**Comment by yutaroyamanaka** [comment]
@apsdehal 
OK, I totally get the point.
Thank you very much !
