### ISSUE TITLE
What is the average accuracy?

### ISSUE THREAD

**Issue by curry111** [facebookresearch/pythia#23]
`>  avg_accuracy += (1 - accuracy_decay) * (accuracy - avg_accuracy)`

I tired to search about "average accuracy" but I didn't find anything useful. I didn't find that in the paper also 
Can anyone please tell me what this line is? and what is the "average accuracy"? Does it have multiple names in the literature because I did not find anything similar to it before?   
I am not a deep learning expert  so maybe I need to learn those :sweat_smile: .

**Comment by YuJiang01** [comment]
it is just a metric for monitoring the program.
