### ISSUE TITLE
Running inference on a custom Json input

### ISSUE THREAD

**Issue by gokulanv** [facebookresearch/pythia#235]
## ❓ Questions and Help

I have a custom Json input on which I would like to run inference on the M4C Captioner model. How do I feed in the custom Json or custom set of images?
@ronghanghu @apsdehal Can you please help?

**Comment by ronghanghu** [comment]
For a custom set of images, the easiest way should be to convert these images to an imdb following the M4C format, and extracting their features following https://github.com/facebookresearch/pythia/tree/project/m4c/projects/M4C#getting-data.

Note that one has to extract OCR results on the images. One may use the Google OCR implementation: https://cloud.google.com/products/ai/

**Comment by gokulanv** [comment]
Lets say we would like to run m4c text caps on the TextVQA images. Can you please suggest how that can be done?

**Comment by ronghanghu** [comment]
In this case, it would be rather easy -- the TextCaps dataset uses the same set of images as in TextVQA (both are built upon Open Images), so one can just run inference on the TextCaps imdbs and match the results to TextVQA using image id.

**Comment by gokulanv** [comment]
Cool, thank you so much. I will try that out now.

**Comment by gokulanv** [comment]
@ronghanghu Thank you for this. I am closing this issue.
