### ISSUE TITLE
Unable to download validation splits

### ISSUE THREAD

**Issue by erobic** [facebookresearch/pythia#24]
```wget https://s3-us-west-1.amazonaws.com/vqa-suite/val_split/v2_OpenEnded_mscoco_minival2014_questions.json``` is causing a 404 error.

**Comment by meetshah1995** [comment]
Sorry about that, we're looking into that. 

Meanwhile you can generate the `minival` and `val2train` split by simply using [this](https://github.com/facebookresearch/pythia/blob/master/tools/subset_val.py) script.

**Comment by YuJiang01** [comment]
we removed the bucket vqa-suite, please use this link: https://s3-us-west-1.amazonaws.com/pythia-vqa/val_split/v2_OpenEnded_mscoco_minival2014_questions.json
