### ISSUE TITLE
Are the different kinds of attention in "image_attention.py" redundant? 

### ISSUE THREAD

**Issue by curry111** [facebookresearch/pythia#25]
Hi :sweat_smile: 
In `image_attention.py` There are three classes 
```
concatenate_attention
project_attention
double_project_attention
```
But they are not being used at all and there is no place for them to be called in the code from other file or function.(I think we don't need them because we use the MFH model)
We only uses `top_down_attention` class in the `build_image_attention_module` function.
My questions are, Are they redundant? and If we wanted to use the ordinary `concatenate_attention` or `project_attention` should I modify the `build_image_attention_module` function to
```
return concatenate_attention(image_feat_dim, txt_rnn_embeding_dim, hidden_size)
```
?

**Comment by YuJiang01** [comment]
yes, currently we didnot use different attention mechanism
