### ISSUE TITLE
404 File not found when downloading VQA2.0

### ISSUE THREAD

**Issue by fliu2013** [facebookresearch/pythia#28]
Hi, guys!
I was wondering why Annotations and Questions in VQA2.0 were unaccessible to me. I got 
`ERROR 404: Not Found.`
when running file `download_vqa_2.0.sh`.
Any advice? Thanks!

**Comment by meetshah1995** [comment]
Download locations were changed for VQA dataset.

Have reflected the updates the paths now in latest commit.
