### ISSUE TITLE
pythia/top_down_bottom_up/classifier.py

### ISSUE THREAD

**Issue by Mohammed-Deifallah** [facebookresearch/pythia#31]
https://github.com/facebookresearch/pythia/blob/18cd8b9c23db229d8e0e55b0a6c2d337cb66d2e3/top_down_bottom_up/classifier.py#L38

How this line works well? I think the right way is to check for 'pretrained_text' in kwargs, not 'pretrained_image'.

**Comment by apsdehal** [comment]
No longer applicable in new version. Closing for now.
