### ISSUE TITLE
fc7_w.pkl not found

### ISSUE THREAD

**Issue by ThegreatShible** [facebookresearch/pythia#34]
I am trying to run the vqa_standalone_image_demo. I have followed the steps to preprocess the data. But I there are some files apparently necessary, but there is no mention how to get them.
fc7_w.pkl and fc7_b.pkl are the one i am stuck with.

**Comment by omarahmed10** [comment]
You can find those files in detectron_fix_100 you can get this folder using
`
wget https://dl.fbaipublicfiles.com/pythia/features/detectron_fix_100.tar.gz
tar -xzf detectron_fix_100.tar.gz
`
Note: this folder is ~400GB after extraction

**Comment by endernewton** [comment]
Thanks @omarahmed10, @meetshah1995 we can probably make the weight files separate from the feature ones?

**Comment by TheShadow29** [comment]
Here are the fc7 files (https://drive.google.com/open?id=1jp47MdcnJ3okZku0PJbWmlY6cCHfusaK) to avoid having to download and unzip the `detectron_fix_100.tar.gz`. It contains `fc7_b.pkl` and `fc7_w.pkl`. Add these to `data/detectron_fix_100/fc6/` and the demo should be working after that.
