### ISSUE TITLE
when will you add bounding box?

### ISSUE THREAD

**Issue by gaopeng-eugene** [facebookresearch/pythia#35]

**Comment by aligholami** [comment]
@gaopeng-eugene Would you elaborate a bit more on the question? What do you mean by a bounding box? Attentions may have bounding boxes, detected objects or something else is what you mean? Thanks.

**Comment by apsdehal** [comment]
Currently, we don't have plans for releasing bounding boxes for VQA 2.0 as we don't use them, maybe in future we will add support. But you can extract out your own features with bounding boxes if you want. TextVQA dataset has bounding boxes for both images as well as OCR boxes if that helps.
