### ISSUE TITLE
size of rcnn_10_100.tar.gz

### ISSUE THREAD

**Issue by McGinn7** [facebookresearch/pythia#36]
I download **rcnn_10_100.tar.gz** twice, and find that it's size is about 33.8 GB.
But it should be 71.0 GB according to **AWS s3 dataset summary**.

**Comment by meetshah1995** [comment]
Thanks for pointing out. I will look into it and update the file if needed.

**Comment by fliu2013** [comment]
@meetshah1995 Also, I can't download detectron.tar.gz from：https://dl.fbaipublicfiles.com/pythia/features/detectron.tar.gz
Quick start only provides path for downloading detectron_fix_100.tar.gz

**Comment by apsdehal** [comment]
Please use newer links in updated README to download the same. Reopen if the issue still persists.
