### ISSUE TITLE
data_preprocess

### ISSUE THREAD

**Issue by McGinn7** [facebookresearch/pythia#37]
In the step **Preprocess dataset**，the first command is `cd ../../VQA_suite`.
But there is no such directory，I create the directory and run following commands.
First, I run command `python data_prep/vqa_v2.0/extract_vocabulary.py --input_files ../orig_data/vqa_v2.0/v2_OpenEnded_mscoco_train2014_questions.json  ../orig_data/vqa_v2.0/v2_OpenEnded_mscoco_val2014_questions.json  ../orig_data/vqa_v2.0/v2_OpenEnded_mscoco_test2015_questions.json --out_dir data/`
directly, and the result is "python: can't open file 'data_prep/vqa_v2.0/extract_vocabulary.py': [Errno 2] No such file or directory"

So I change the cmd and run `python ../data_prep/vqa_v2.0/extract_vocabulary.py --input_files ../orig_data/vqa_v2.0/v2_OpenEnded_mscoco_train2014_questions.json  ../orig_data/vqa_v2.0/v2_OpenEnded_mscoco_val2014_questions.json  ../orig_data/vqa_v2.0/v2_OpenEnded_mscoco_test2015_questions.json --out_dir data/`
and result is "Traceback (most recent call last):
  File "../data_prep/vqa_v2.0/extract_vocabulary.py", line 13, in <module>
    from dataset_utils.text_processing import tokenize
ImportError: No module named dataset_utils.text_processing"

I don't know where is my problem, and need your help. Thanks ahead!

**Comment by fliu2013** [comment]
Maybe you can make subtle changes and  try running in the pythia directory.

**Comment by McGinn7** [comment]
> Maybe you can make subtle changes and try running in the pythia directory.

Thank you! 
I try running in the pythia directory, and the cmd is `python data_prep/vqa_v2.0/extract_vocabulary.py --input_files ./orig_data/vqa_v2.0/v2_OpenEnded_mscoco_train2014_questions.json  ./orig_data/vqa_v2.0/v2_OpenEnded_mscoco_val2014_questions.json  ./orig_data/vqa_v2.0/v2_OpenEnded_mscoco_test2015_questions.json --out_dir data/`
