### ISSUE TITLE
Ask for more models to extract features

### ISSUE THREAD

**Issue by HuaizhengZhang** [facebookresearch/pythia#38]
It seems that the data preprocessing guide only provides a pre-trained fast_rcnn model. Do you have any plans to release the other pre-trained models like faster_rcnn? Thank you so much.

https://github.com/facebookresearch/pythia/blob/a494706946af278da37db4de367c62d827eacf08/data_prep/data_preprocess.md

**Comment by aligholami** [comment]
I think that should be quite simple. Since the framework is **modular**. Its just another pre-trained model that maps every image to a bunch of images (of objects) and extracts their feature maps. Saving is the same. Loading the model is the same. I hope it will be added soon.
