### ISSUE TITLE
Can we have suppport for CPU based demo for pythia?

### ISSUE THREAD

**Issue by fristonio** [facebookresearch/pythia#4]
It would be great if we can have support for CPU based demo for pythia.

**Comment by endernewton** [comment]
We are actively working on a CPU demo now. Thanks for the patience.

**Comment by apsdehal** [comment]
This should now be fixed with Colab demo. Alternatively, pretrained models can also be run on CPU.

**Comment by brentbiseda** [comment]
Can you please provide an example of CPU inference?

**Comment by apsdehal** [comment]
Append this behind your command : `training_parameters.device cpu`. So, if your command is `[command]`, use `[command] training_parameters.device cpu`.
