### ISSUE TITLE
Using detectron features

### ISSUE THREAD

**Issue by yarinKuper** [facebookresearch/pythia#40]
Hi,

I am trying to run the model and i am unable to download the detectron or the detectron_fix_100 (gunzip detectron_fix_100.tar.gz outputs gzip: detectron_fix_100.tar.gz: Input/output error), is there different link to the detectron features? 

Thanks!

**Comment by apsdehal** [comment]
The newer version contains updated links to the same. Please reopen the issue if it still persists.
