### ISSUE TITLE
Pretrained model performance?

### ISSUE THREAD

**Issue by TheShadow29** [facebookresearch/pythia#45]
Hi. Thanks for the resourceful repository. 

I was wondering if you could share the pre-trained model performances for the validation and the test sets for the various datasets.

**Comment by apsdehal** [comment]
Hi,

Yes, we plan to add them to pretrained models section in documentation and Readme. Expect an update from me soon.

**Comment by apsdehal** [comment]
Performance tables have been added to README and documentation. Please feel free to reopen if something is not clear. Thanks.
