### ISSUE TITLE
image dataset to .npy

### ISSUE THREAD

**Issue by virginie-do** [facebookresearch/pythia#49]
How did you transform the vqa dataset to a .npy file available for download?

**Comment by meetshah1995** [comment]
The documentation about converting VQA dataset to the npy files provided is described [here](https://github.com/facebookresearch/pythia/blob/master/pythia/legacy/data_prep/data_preprocess.md)

Kindly close the issue if you feel your query has been answered.

**Comment by apsdehal** [comment]
In simple terms, you put metadata as dict on first line and each question and its related data's dict on a separate line. 

For saving, push all these dicts in an array and save using `np.save`.

**Comment by virginie-do** [comment]
Thank you. 

> The documentation about converting VQA dataset to the npy files provided is described [here](https://github.com/facebookresearch/pythia/blob/master/pythia/legacy/data_prep/data_preprocess.md)

Are these scripts mentioned in the Readme available somewhere?
`data_prep/vqa_v2.0/build_vqa_2.0_imdb.py`
`data_prep/vqa_v2.0/extract_word_glove_embedding.py`
`data_prep/vqa_v2.0/download_vqa_2.0.sh`

**Comment by apsdehal** [comment]
Yup, they are in this folder: https://github.com/facebookresearch/pythia/tree/master/pythia/legacy/data_prep/vqa_v2.0

**Comment by apsdehal** [comment]
Closing as resolved. @virginie-do if you have any other questions please open up a new issue.
