### ISSUE TITLE
Unexpected EOF on extracting data tar

### ISSUE THREAD

**Issue by goyalsaransh97** [facebookresearch/pythia#53]
I am getting unexpected EOF on extracting the tar file from https://dl.fbaipublicfiles.com/pythia/features/coco.tar.gz.
Could someone please help?

**Comment by apsdehal** [comment]
Can you post output of `du -sh *`?
It is probably incomplete download size.

**Comment by meetshah1995** [comment]
Since these files are quite large it'd be great to add md5 checksums for them. I'll add them to the readme tonight.

**Comment by goyalsaransh97** [comment]
Yes, the file was small in size. I re-downloaded it. It's working fine now, thanks.
