### ISSUE TITLE
Inference on K40m GPU

### ISSUE THREAD

**Issue by goyalsaransh97** [facebookresearch/pythia#58]
I tried running inference for pre-trained pythia mdoel on K40m. It didn't start for quite some time and then the ETA was oscillating around 10-15 hours. 
So I enabled multi-GPU training using dataparallel flag. But now its not starting, I've waited for around 30 minutes before stopping it. I got the following errors on stopping:
"
File "/mnt/data_g/saransh/anaconda3/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
elif lock.acquire(block, timeout):
".
I've tried re-running it but the problem persists. Earlier I tried it on a V100, it was working fine on that.
Could you suggest something?

**Comment by apsdehal** [comment]
Hard to say without testing on k40m. But for now can you try setting `training_parameters.num_workers` to 0.

**Comment by goyalsaransh97** [comment]
The problem persists after adding the numworkers flag.

**Comment by apsdehal** [comment]
Following https://bugs.launchpad.net/designate/+bug/1782647, it seems like a bug with 3.7, can you try with 3.6?

**Comment by apsdehal** [comment]
Related: https://github.com/pytorch/pytorch/issues/8388

**Comment by goyalsaransh97** [comment]
Thanks for your help.
