### ISSUE TITLE
Getting Object Labels

### ISSUE THREAD

**Issue by goyalsaransh97** [facebookresearch/pythia#59]
Is there a way for getting the object labels for bounding boxes, given by the (fine-tuned) Detectron model?

**Comment by apsdehal** [comment]
Currently, we don't have this data present in our object features. You can check Colab demo to understand how to extract object features and every other information at your end. You can also look into maskrcnn-benchmark for extracting object features.

For TextVQA, we have some information including bounding boxes coordinates and other stuff in info files but it still doesn't contain object labels. We probably won't be fixing this in near future.

**Comment by goyalsaransh97** [comment]
Precisely which model(and version) are you using for object detection?

**Comment by apsdehal** [comment]
You can use the script here and follow the instructions to install. Comment out the lines to get all the relevant data other than features:
https://github.com/facebookresearch/pythia/blob/master/tools/extract_features.py#L190-L198
