### ISSUE TITLE
How can we extract image features instead of downloading  large files?

### ISSUE THREAD

**Issue by lhwcv** [facebookresearch/pythia#6]
Can pythia provide pretrained  image feature model thus we  extract the features from the original image,  no  need to download image features' file , that's pretty large.    Thank you!

**Comment by endernewton** [comment]
How long does it take to download the feature files now? If it can solve your problem, we can upload the features to somewhere that are easy for you to download.

**Comment by lhwcv** [comment]
@endernewton  Upload to BaiduYun maybe?   Thank you very much!

**Comment by YuJiang01** [comment]
Add help information under [data_prep/data_preprocess.md](data_prep/data_preprocess.md),

**Comment by lhwcv** [comment]
@YuJiang01   Thanks!

**Comment by wangpengnorman** [comment]
Hi, I want to extract image features, however, "data_prep/data_preprocess.md" is not available any more.

**Comment by apsdehal** [comment]
@wangpengnorman check https://github.com/facebookresearch/pythia/blob/0.1/data_prep/data_preprocess.md in branch 0.1.
