### ISSUE TITLE
m5sum checksum target values in wrong order?

### ISSUE THREAD

**Issue by IgorBrehm-Lis** [facebookresearch/pythia#61]
Hi, I downloaded yesterday the coco.tar.gz features file (240GB) and when I made the md5sum checksum I got _ab7947b04f3063c774b87dfbf4d0e981_ instead of the target _b22e80997b2580edaf08d7e3a896e324_ value. The funny thing is that _ab7947b04f3063c774b87dfbf4d0e981_ is the target value said to belong to the OpenImages features file, so I believe the target values where misplaced by accident. Is that correct? Thanks.

**Comment by meetshah1995** [comment]
Yes, thanks for pointing. 

Fixed in aa8b8c0
