### ISSUE TITLE
Training Lorra on VQA2

### ISSUE THREAD

**Issue by goyalsaransh97** [facebookresearch/pythia#68]
I'm trying to train Lorra model for VQA2 dataset but I'm getting the following error 
ValueError: /raid/saransh/pythia/pythia/.vector_cache/wiki.en.bin cannot be opened for loading!

**Comment by apsdehal** [comment]
How are you running this? It should automatically download this file.

**Comment by apsdehal** [comment]
For now you can also download it from https://dl.fbaipublicfiles.com/pythia/pretrained_models/fasttext/wiki.en.bin

**Comment by goyalsaransh97** [comment]
I simply changed the yml file and name of model in the training command. Should I have done something else?

**Comment by apsdehal** [comment]
Can you post your exact command here so it is easy to debug?

**Comment by goyalsaransh97** [comment]
The exact command was
python tools/run.py --tasks vqa --datasets vqa2 --model lorra --config configs/vqa/vqa2/lorra.yml
I've downloaded the file and will start training tomorrow. Right now, I'm training the BAN model.
Also, what are the approx. scores I should expect for BAN and pythia models?

**Comment by goyalsaransh97** [comment]
Also, on training the model(BAN or Pythia), I'm getting the following warning at the end:
2019-05-28T19:37:47 WARNING: /raid/saransh/pythia/pythia/modules/losses.py:88: UserWarning: Sample list has not field 'targets', are you sure that your ImDB has labels? you may have wanted to run with --evalai_inference 1
  warnings.warn("Sample list has not field 'targets', are you "

2019-05-28T19:49:16 INFO: vqa2: full test:, 22001/22000, test/total_loss: 0.0000

**Comment by apsdehal** [comment]
That warning is expected as if you run code without `--evalai_inference 1` and `--run_type` has inference option set, it will try to run the inference code. But, since if doesn't have any targets it can't compare predictions.

**Comment by apsdehal** [comment]
Pythia and BAN accuracies are reported in the TextVQA paper. https://arxiv.org/abs/1904.08920

**Comment by goyalsaransh97** [comment]
I've trained the models and reproduced(approx.) results on test-dev.
Thanks for your continued support.

**Comment by abhinavkcs11** [comment]
> --evalai_inference 1



> I've trained the models and reproduced(approx.) results on test-dev. Thanks for your continued support.

@goyalsaransh97 can you share the exact command to for training?
