### ISSUE TITLE
Question on TextVQA  - Pythia vs LoRRA

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/pythia#69]
Hey

I have few questions on the ablation studies conducted for the LoRRA model.

In Table 2  in the TextVQA paper , what is  the difference between  `Pythia + O + C` and `Pythia + LoRRA`. Is it that the second one also gets to choose its answers from a fixed lexicon ( either SA or LA)? Is it the only difference between the two?

While reading section 3 of the paper  I get a feel that `LoRRA` has a VQA part ( image + question) and a reading part ( OCR tokens + question) and an answering module. This suggests that by `LoRRA` you mean the complete system. But in experiments `Pythia + LoRRA` is used to denote the best performing model. This nomenclature is bit confusing. Does it mean that to an existing `Pythia` style model you again add  `LoRRA` which on its own has a vqa + reading + answering modules ?

**Comment by apsdehal** [comment]
Yes, as you mentioned the difference is ability to choose from fixed answer space as well. The final model we have we call it LoRRA, for easy comparison and terminology.

Pythia + LORRA'S VQA component is Pythia and rest of the stuff is specific to Lorra module. We had to use this nomenclature to differentiate between BAN + LoRRA and Pythia + LoRRA.
