### ISSUE TITLE
Could you provide the result for the pythia_12k_iterations_no_resnet.yml  configuration?

### ISSUE THREAD

**Issue by liunian-harold-li** [facebookresearch/pythia#72]
Hi, could you provide the results (text-dev/test-std accuracy) for the pythia_12k_iterations_no_resnet.yml configuration? I wasn't able to find the corresponding result of that model in the Pythia paper (https://arxiv.org/pdf/1807.09956.pdf). I would greatly appreciate your help!

In addition, is it convenient for you to provide the adaptive detectron features (presumably the detectron.tar.gz file)?

Thanks!

**Comment by apsdehal** [comment]
I don't have results on that configuration handy. To reproduce the results on original paper (the ensembles and the ones with extra data) use v0.1 branch. The current master only contains single models and corresponds to new pythia version introduced in https://arxiv.org/abs/1904.08920. 

The detectron.tar.gz is the same as COCO features, the link for which you can find in Readme.

**Comment by liunian-harold-li** [comment]
Thanks for the prompt response! That's really helpful!

It seems that the COCO feature file contains detectron_fix_100 and resnet152. The detectron_fix_100 has 100 features for each image. But from my understanding, in the original paper, there is a model using **adaptive** detectron features (not always 100 features for each image) and no ensembles or extra data (Detectron & Fine-tuning (§2.3) 68.49). 

I wonder if you could provide the features for that model. Those features seem to be present in the V0.1 branch, called the  detectron.tar.gz (106.2 GB), but there is no link to download it (The detectron_fix_100.tar.gz is 162.6GB).

Thanks!

**Comment by apsdehal** [comment]
If you are looking to reproduce the best single model, please use fixed 100 bounding boxes and the current master branch. According to our experiments fixed 100 bounding boxes work better than adaptive ones. 

The current master branch's pythia train and gal model will be able to give you similar accuracy when trained.

**Comment by liunian-harold-li** [comment]
Thank you for the response! I will use the fixed-100 features. Just want to note that it might be helpful to have the adaptive features or the score for pythia_12k_iterations_no_resnet.yml but that's not an urgent request. 

Sorry for the trouble!

**Comment by apsdehal** [comment]
@liunian-harold-li I trained the model on pythia_12k_iterations_no_resnet.yml configuration and found the result to be 68.84. https://evalai.s3.amazonaws.com/media/submission_files/submission_23567/4d3990e1-a93a-458e-ba96-7735ed02c0ef.json. I hope this helps.

**Comment by liunian-harold-li** [comment]
Thank you very much! That's quite helpful!
