### ISSUE TITLE
Eval test set

### ISSUE THREAD

**Issue by LousyLory** [facebookresearch/pythia#90]
Hi,

I'm sorry if this seems super dumb. I used then pre-trained model to generate JSON file for VQA2.0 using pythia. Since it just gets us the answers and not a score, I tried uploading the results in https://competitions.codalab.org/competitions/6961#participate-submit_results. I am always getting the following error:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmp9OMs9h/run/program/evaluate.py", line 96, in 
    resFile = glob.glob(resFileFmt)[0]
IndexError: list index out of range

(I understand this can be a file-not-found error)

I used the following command to generate this output:
python tools/run.py --tasks vqa --datasets vqa2 --model pythia --config configs/vqa/vqa2/pythia_train_and_val.yml --run_type inference --evalai_inference 1 --resume_file data/models/pythia_train_val.pth

Also I did check all the issues mentioned in https://competitions.codalab.org/competitions/6961#participate-submit_results and followed instruction strictly. Please let me know if I am doing something incorrect or if there's another way to numerically evaluate the results (also let me know if you need more information on this).

Thanks,
Archan

**Comment by apsdehal** [comment]
@LousyLory The JSON file generated from Pythia is for VQA2.0 while the codalab is for VQA1.0 evaluation. I believe you wanted to use EvalAI for VQA2.0 evaluation? https://evalai.cloudcv.org/web/challenges/challenge-page/163/overview

**Comment by LousyLory** [comment]
Okay that worked. Thanks! (and apologies for being naive)
