### ISSUE TITLE
Generative Decoder

### ISSUE THREAD

**Issue by shubhamagarwal92** [facebookresearch/pythia#91]
## ❓ Questions and Help

Do we also have a generative decoder here? Can you point me to the path. 

I can only see the discriminative decoder [here](https://github.com/shubhamagarwal92/pythia/blob/master/pythia/modules/decoders.py)

**Comment by apsdehal** [comment]
We do have one that was introduced in captioning PR. Check https://github.com/facebookresearch/pythia/blob/master/pythia/modules/decoders.py#L54. This is quite generic and should be able to handle most of the cases. Let us know if this doesn't work for your use-case.
