### ISSUE TITLE
About OCR features

### ISSUE THREAD

**Issue by Dawitmu** [facebookresearch/pythia#95]
## ❓ Questions and Help
Within the lorra.py code, there is a sample_list. Is the OCR features within this list? if yes, which one is it? or where are they located?

**Comment by apsdehal** [comment]
Hi,
They should be inside `sample_list.context`. You can print the sample list to see its contents.

**Comment by apsdehal** [comment]
Closing as I believe this has been resolved. Please open up a new issue if you face any other problems.
