### ISSUE TITLE
is there anyway I can choose the GPUs to use in config

### ISSUE THREAD

**Issue by LousyLory** [facebookresearch/pythia#97]
I am trying to train LoRRA for VQA2.0. When I set data_parallel to 1 the code grabs all the GPUs available to me. Is there any setting in config which I can use to use certain GPUs and leave others free?
 I am using the following command to train LoRRA: `python tools/run.py --tasks vqa --datasets vqa2 --model lorra --config configs/vqa/vqa2/lorra_train_and_val.yml --data_parallel 1 --device cuda`

I assume local_rank is for distributed setting.

**Comment by apsdehal** [comment]
Hi,
We don't directly support as it possible to support this using env vars. See https://discuss.pytorch.org/t/select-gpu-device-through-env-vars/318.

So, basically if you want to use device 0 and 1, do `CUDA_VISIBLE_DEVICES=0,1 [command] here`.

**Comment by LousyLory** [comment]
Worked! I thought I was missing some setting from the config flags. I guess it would be useful if you add this to the documentation (just a suggestion).

**Comment by apsdehal** [comment]
Sure. Once I complete distributed related changes, I plan to write a separate documentation on multi-gpu training. I will mention this there. Closing for now.
