### ISSUE TITLE
Object class of detectron?

### ISSUE THREAD

**Issue by ggaemo** [facebookresearch/pythia#98]
## ❓ Questions and Help
What are the value of the objects that are given by the detectron? I am trying to use the code in tools/extract_features.py

Only indices are given and the actual <idx2class > are not given.
It is the objects variable in the following code snippet.
It has 1601 classes. Where can I find the dictionary of index to vocab?

Thank you.

`   
with c2_utils.NamedCudaScope(0):
        scores, cls_boxes, im_scale = infer_engine.im_detect_bbox(
            model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=bboxes
        )

        box_features = workspace.FetchBlob(feat_blob_name)
        cls_prob = workspace.FetchBlob("gpu_0/cls_prob")
        rois = workspace.FetchBlob("gpu_0/rois")
        max_conf = np.zeros((rois.shape[0]))
        # unscale back to raw image space
        cls_boxes = rois[:, 1:5] / im_scale

        for cls_ind in range(1, cls_prob.shape[1]):
            cls_scores = scores[:, cls_ind]
            dets = np.hstack((cls_boxes, cls_scores[:, np.newaxis])).astype(np.float32)
            keep = np.array(nms(dets, cfg.TEST.NMS))
            max_conf[keep] = np.where(
                cls_scores[keep] > max_conf[keep], cls_scores[keep], max_conf[keep]
            )
        keep_boxes = np.where(max_conf >= conf_thresh)[0]
        if len(keep_boxes) < MIN_BOXES:
            keep_boxes = np.argsort(max_conf)[::-1][:MIN_BOXES]
        elif len(keep_boxes) > MAX_BOXES:
            keep_boxes = np.argsort(max_conf)[::-1][:MAX_BOXES]
        objects = np.argmax(cls_prob[keep_boxes], axis=1)

    return box_features[keep_boxes]
`

**Comment by endernewton** [comment]
It is at: https://github.com/peteanderson80/bottom-up-attention/tree/master/data/genome/1600-400-20
You can find objects and attributes list there.

**Comment by apsdehal** [comment]
Thanks @endernewton, also direct link here for future reference: https://dl.fbaipublicfiles.com/pythia/data/visual_genome_categories.json

**Comment by ggaemo** [comment]
Thank you so much!! Just one more thing. The object scores have 1601 categories. Does the first category correspond to the background?

**Comment by apsdehal** [comment]
Yes, you are right.
